const $ = selector => document.querySelector(selector);
let model = null;
let selectedIds = new Set();
let query = "";
let toastTimer;
let queueFilter = "all";
let lastStatusAt = "";
let identityBusy = false;
let identityFormSession = "";
const reviewFields = [
  ["category_and_attributes", "淘宝真实类目及完整属性"],
  ["supply_and_qualification", "真实供给与所需资质"],
  ["price_refund_fulfillment", "价格、退改、售后与履约"],
  ["destination_assets", "目的地与主图、副图、详情一致性"],
  ["dry_run_mapping", "当前页面的 DRY_RUN 字段映射证据"]
];
const isolatablePauseSteps = new Set(["PACKAGE_MISSING", "PACKAGE_REVALIDATION_FAILED", "PACKAGE_CHANGED_SINCE_REVIEW", "PACKAGE_SNAPSHOT_MISSING", "REVIEW_REVALIDATION_FAILED", "SHOP_REVALIDATION_FAILED", "MAPPING_INVALID", "MAPPING_CHANGED_SINCE_REVIEW", "MAPPING_SNAPSHOT_MISSING", "FIELD_VALUE_MISSING", "PAGE_OR_MAPPING_PAUSED", "DUPLICATE_LISTING_DETECTED"]);

function log(message) { const now = new Date().toLocaleTimeString("zh-CN", { hour12: false }); $("#log").textContent = `[${now}] ${message}\n` + $("#log").textContent; }
function toast(message) { const node = $("#toast"); node.textContent = message; node.classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(() => node.classList.remove("show"), 3600); }
async function api(path, options = {}) { const response = await fetch(path, { headers: { "content-type": "application/json" }, ...options }); const data = await response.json(); if (!response.ok) { if (data.browser && model) { model.browser = data.browser; renderAll(); } throw new Error(data.error || "请求失败"); } return data; }
function jobs() { return model?.state?.jobs || []; }
function tasks() { return model?.state?.tasks || []; }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>'"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]); }
function jobMatchesCurrentStore(job) { return !job.profile?.shop_name || job.profile.shop_name === model.activeShop.name; }
function filteredJobs() { const text = query.trim().toLocaleLowerCase(); return jobs().filter(job => { const matchesText = !text || [job.destination, job.title, job.profile?.shop_name, job.sourceFile].filter(Boolean).join(" ").toLocaleLowerCase().includes(text); const state = preflight(job).state; const matchesFilter = queueFilter === "all" || (queueFilter === "ready" && state === "ready") || (queueFilter === "blocked" && state !== "ready"); return matchesText && matchesFilter; }); }
function updateSaveState(text = "本地已保存") { $("#saveState").textContent = text; }
function setBrowser(browser, installed) {
  const connected = browser.connected === true, owned = browser.ownershipVerified === true, ready = browser.canExecute === true, shop = model.activeShop;
  const label = browser.loginState === "PAUSED_CAPTCHA" ? "等待人工验证" : browser.loggedIn ? "已登录" : browser.running ? "等待人工登录" : connected ? "旧会话未接管" : installed ? "待启动" : "未安装 Chrome";
  $("#browserBadge").textContent = label; $("#browserBadge").className = `badge ${ready ? "success" : "muted"}`;
  $("#sessionStore").textContent = shop.name;
  $("#sessionDetail").textContent = browser.reason || (ready ? "当前草稿页的店铺身份已核验；执行前会再次检查。" : "请启动专用 Chrome，登录后打开正确草稿页并核验店铺。");
  $("#sessionChecks").textContent = `浏览器：${browser.running ? "运行中" : "未运行"} · 登录：${browser.loggedIn ? "已登录" : "未验证"} · ${browser.persistent ? "项目专用状态持续保存" : "会话待核验"}`;
  $("#openSeller").disabled = !connected || !owned;
  $("#browserStatusLabel").textContent = connected ? "专用 Chrome 已连接" : "专用 Chrome 未连接";
  $("#browserStatusValue").textContent = `${shop.name} · ${label}`;
  $("#browserStatusText").textContent = ready ? "身份核验仅适用于当前草稿页，不代表商品审核或发布授权。" : $("#sessionDetail").textContent;
  $("#sessionPulse").classList.toggle("connected", ready); $("#sideStoreName").textContent = shop.name; $("#sideStoreState").textContent = label;
  const formSession = `${shop.id}:${browser.sessionId || ""}`;
  if (identityFormSession !== formSession) { $("#identityForm").reset(); $("#identityFeedback").textContent = ""; identityFormSession = formSession; }
  $("#confirmIdentity").disabled = identityBusy || !browser.canConfirmIdentity || !browser.sessionId;
}
function showIdentityForm() {
  $("#identityDetails").open = true; $("#identityDetails").scrollIntoView({ behavior: "smooth", block: "center" }); $("#identityShopName").focus({ preventScroll: true });
}
async function confirmIdentity(event) {
  event.preventDefault();
  const browser = model?.browser, feedback = $("#identityFeedback");
  if (!browser?.canConfirmIdentity || !browser.sessionId || identityBusy) { feedback.textContent = browser?.reason || "当前会话不可核验，请刷新状态后重试。"; return; }
  const shopName = $("#identityShopName").value.trim(), identitySelector = $("#identitySelector").value.trim();
  if (!shopName || !identitySelector || !$("#identityReviewed").checked) { feedback.textContent = "请填写后台店铺名与已核验的定位器，并勾选人工核对。"; return; }
  identityBusy = true; $("#confirmIdentity").disabled = true; feedback.textContent = "正在检查当前草稿页的店铺名称…";
  try {
    const data = await api("/api/chrome/confirm-identity", { method: "POST", body: JSON.stringify({ sessionId: browser.sessionId, shopName, identitySelector, reviewed: true }) });
    model.browser = data.browser; renderAll(); feedback.textContent = data.browser.canExecute ? "当前草稿页身份核验已完成；商品审核与发布闸门仍需分别通过。" : data.browser.reason || "核验未通过，请检查当前草稿页。";
    $("#identityReviewed").checked = false;
  } catch (error) { feedback.textContent = error.message; $("#identityReviewed").checked = false; await refresh({ quiet: true }); }
  finally { identityBusy = false; setBrowser(model.browser, model.chromeInstalled); }
}
function renderShops() { const select = $("#shopSelect"); select.replaceChildren(); for (const shop of model.shops) { const option = document.createElement("option"); option.value = shop.id; option.textContent = `${shop.name} · 独立会话`; option.selected = shop.id === model.activeShop.id; select.append(option); } }
function renderMetrics() { const all = jobs(), selected = [...selectedIds].filter(id => all.some(job => job.id === id)).length, draftable = all.filter(job => preflight(job).state === "ready").length; $("#readyCount").textContent = all.length; $("#selectedCount").textContent = selected; $("#batchAvailable").textContent = draftable; $("#blockedCount").textContent = all.length - draftable; }
function eventTime(value) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString("zh-CN", { hour12: false, month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }); }
function evidenceHref(value) { const source = String(value || ""); if (source.startsWith("output/")) return `./${source}`; if (/^https?:\/\//i.test(source)) return source; return null; }
function sourceName(value) { const source = String(value || ""); return source.split(/[\\/]/).filter(Boolean).pop() || "未提供"; }
function titleVersions(job) { const raw = job.listing?.title_versions || job.listing?.title_candidates || job.listing?.titles || [job.title]; const items = Array.isArray(raw) ? raw : [raw]; return [...new Set(items.map(item => typeof item === "string" ? item.trim() : String(item?.title || "").trim()).filter(Boolean))]; }
function canIsolateItem(task) { return task.state === "PAUSED" && isolatablePauseSteps.has(task.currentStep); }
function renderTasks() {
  const body = $("#tasks"), list = tasks(), queued = list.filter(task => task.state === "QUEUED").length, paused = list.filter(task => task.state === "PAUSED").length; body.replaceChildren(); $("#taskCount").textContent = `${list.length} 个任务 · 队列 ${queued} · 暂停 ${paused}`;
  if (!list.length) { body.innerHTML = '<tr><td colspan="5" class="empty-state">尚未创建 DRY_RUN 任务。</td></tr>'; return; }
  for (const task of list) {
    const row = document.createElement("tr"), latest = task.events?.[0], canQueue = task.state === "WAITING_FOR_REVIEW", canResume = task.state === "PAUSED" && ["PAUSED_RISK_CONTROL", "RISK_PAUSED"].includes(task.currentStep), canStop = !["COMPLETED", "COMPLETED_WITH_ISOLATIONS", "FAILED", "CANCELLED"].includes(task.state);
    const itemNames = (task.items || []).map(item => item.destination || item.jobId).join("、") || "无商品";
    const stateClass = String(task.state || "").toLowerCase().replace(/[^a-z_]/g, "");
    row.innerHTML = `<td><div class="task-id"><strong>${escapeHtml(task.id)}</strong><small>${escapeHtml(task.shopName || task.shopId || "未指定店铺")} · ${escapeHtml(task.mode)}</small></div></td><td><span class="task-state ${stateClass}">${escapeHtml(task.state)}</span><small class="task-step">${escapeHtml(task.currentStep || "—")}</small></td><td><span class="task-items">${escapeHtml(itemNames)}</span></td><td><div class="task-event"><strong>${escapeHtml(latest?.type || "—")}</strong><small>${escapeHtml(latest ? `${eventTime(latest.at)} · ${latest.message}${latest.evidence ? ` · 证据：${latest.evidence}` : ""}` : "暂无事件")}</small></div></td><td class="action-cell"></td>`;
    const actions = row.querySelector(".action-cell");
    const detail = document.createElement("button"); detail.type = "button"; detail.className = "secondary"; detail.textContent = "查看记录"; detail.addEventListener("click", () => openTaskDetail(task)); actions.append(detail);
    if (task.state === "WAITING_FOR_REVIEW") { const button = document.createElement("button"); button.type = "button"; button.className = "secondary"; button.textContent = "排队"; button.addEventListener("click", () => updateTask(task, "queue")); actions.append(button); }
    if (canResume) { const resume = document.createElement("button"); resume.type = "button"; resume.className = "secondary"; resume.textContent = "记录处理后恢复"; resume.addEventListener("click", () => openRecovery(task)); actions.append(resume); }
    if (task.state === "PAUSED" && task.currentStep === "MANUAL_FIELD_REQUIRED") { actions.replaceChildren(detail); const acknowledge = document.createElement("button"); acknowledge.type = "button"; acknowledge.className = "primary"; acknowledge.textContent = "确认已人工填写"; acknowledge.addEventListener("click", () => updateTask(task, "acknowledge-manual")); actions.append(acknowledge); }
    if (task.state === "PAUSED" && task.currentStep === "FINAL_REVIEW_REQUIRED") { actions.replaceChildren(detail); const complete = document.createElement("button"); complete.type = "button"; complete.className = "primary"; complete.textContent = "记录草稿核验结论"; complete.addEventListener("click", () => openFinalReview(task)); actions.append(complete); }
    if (canIsolateItem(task)) { const isolate = document.createElement("button"); isolate.type = "button"; isolate.className = "text-action"; isolate.textContent = "隔离本条"; isolate.addEventListener("click", () => openIsolation(task)); actions.append(isolate); }
    if (task.state === "PAUSED" && task.currentStep === "SESSION_REVALIDATION_FAILED") { const recover = document.createElement("button"); recover.type = "button"; recover.className = "primary"; recover.textContent = model.browser.canExecute ? "重新排队" : "重新核验店铺"; recover.addEventListener("click", () => model.browser.canExecute ? updateTask(task, "queue") : showIdentityForm()); actions.append(recover); }
    if (task.state === "QUEUED") { const start = document.createElement("button"); start.type = "button"; start.className = "primary"; start.textContent = "开始 DRY_RUN"; start.disabled = !model.browser.canExecute; start.title = model.browser.canExecute ? "" : model.browser.reason || "请先核验当前草稿页的店铺身份"; start.addEventListener("click", () => updateTask(task, "start")); actions.append(start); }
    if (task.state === "RUNNING") { const pause = document.createElement("button"); pause.type = "button"; pause.className = "secondary"; pause.textContent = "风控/滑块暂停"; pause.addEventListener("click", () => openRisk(task)); actions.append(pause); }
    if (canStop) { const cancel = document.createElement("button"); cancel.type = "button"; cancel.className = "text-action"; cancel.textContent = "取消"; cancel.addEventListener("click", () => updateTask(task, "cancel")); actions.append(cancel); }
    body.append(row);
  }
}
function packageMonitorActions() {
  const currentStore = jobs().filter(jobMatchesCurrentStore), actions = [];
  const wrongStore = jobs().filter(job => !jobMatchesCurrentStore(job));
  if (wrongStore.length) actions.push({ job: wrongStore[0], next: { priority: 1, label: "商品包店铺待切换", detail: `${wrongStore.length} 条商品包属于其它店铺；请先切换到“${wrongStore[0].profile?.shop_name || "对应店铺"}”再继续审核。`, action: "shop" } });
  const statusBlocked = currentStore.filter(job => job.status !== "READY");
  if (statusBlocked.length) actions.push({ job: statusBlocked[0], next: { priority: 1, label: "商品包待确认", detail: `${statusBlocked.length} 条商品包仍为待审核状态；先填入真实资料并完成卖家页核验，再改为 READY。`, action: "preview" } });
  const duplicate = currentStore.filter(job => job.status === "READY" && duplicateListingDetail(job));
  if (duplicate.length) actions.push({ job: duplicate[0], next: { priority: 1, label: "发现同店重复商品", detail: `${duplicate.length} 条商品包与同店国家/城市链接重复；请保留一条后重新导入。`, action: "preview" } });
  const packageBlocked = currentStore.filter(job => job.status === "READY" && !job.packageValidation?.valid);
  if (packageBlocked.length) actions.push({ job: packageBlocked[0], next: { priority: 1, label: "商品包资料待补齐", detail: `${packageBlocked.length} 条商品包未通过标题、目的地或素材规则；请从“${packageBlocked[0].destination}”开始补齐。`, action: "package" } });
  const evidenceBlocked = currentStore.filter(job => job.status === "READY" && job.packageValidation?.valid && (job.releaseBlockers || []).length);
  if (evidenceBlocked.length) actions.push({ job: evidenceBlocked[0], next: { priority: 2, label: "发布审核资料待补充", detail: `${evidenceBlocked.length} 条商品包缺少真实类目、供给、履约或素材证据；保存可复核来源后才能创建草稿任务。`, action: "review" } });
  const mappingBlocked = currentStore.filter(job => job.status === "READY" && job.packageValidation?.valid && !(job.releaseBlockers || []).length && !job.mappingValidation?.valid);
  if (mappingBlocked.length) actions.push({ job: mappingBlocked[0], next: { priority: 2, label: "字段映射待核验", detail: `${mappingBlocked.length} 条商品包缺少已核验的当前卖家页字段映射；不会猜测淘宝定位器。`, action: "mapping" } });
  return actions;
}
function monitorAction(task) {
  if (task.state === "PAUSED" && task.currentStep === "SESSION_REVALIDATION_FAILED") return { priority: 1, label: "会话身份需要重新核验", detail: "请在专用 Chrome 打开本次任务的正确草稿页，重新核验店铺身份后将原任务重新排队。", action: model.browser.canExecute ? "session-queue" : "identity" };
  if (task.state === "PAUSED" && ["PAUSED_RISK_CONTROL", "RISK_PAUSED"].includes(task.currentStep)) return { priority: 0, label: "先处理风控现场", detail: "请在专用 Chrome 完成滑块、验证码或登录验证，再记录处理结果后恢复；工作台不会代为处理。", action: "resume" };
  if (task.state === "PAUSED" && ["PACKAGE_REVALIDATION_FAILED", "PACKAGE_CHANGED_SINCE_REVIEW", "PACKAGE_SNAPSHOT_MISSING"].includes(task.currentStep)) return { priority: 1, label: "商品包资料已变化", detail: "执行前复核发现商品内容已变化或未冻结；重新审核后取消旧任务，再创建新的 DRY_RUN。", action: "package" };
  if (task.state === "PAUSED" && task.currentStep === "REVIEW_REVALIDATION_FAILED") return { priority: 1, label: "审核资料需要重新确认", detail: "五项审核证据已有缺失或变化；补充可复核来源后取消旧任务，再重新创建 DRY_RUN。", action: "review" };
  if (task.state === "PAUSED" && task.currentStep === "DUPLICATE_LISTING_DETECTED") return { priority: 1, label: "发现同店重复商品", detail: "同店同国家或同城市只能保留一个链接。核对商品包后保留一条、重新导入，再新建 DRY_RUN。", action: "preview" };
  if (task.state === "PAUSED" && task.currentStep === "SHOP_REVALIDATION_FAILED") return { priority: 1, label: "当前店铺不匹配", detail: "商品包与当前专用 Chrome 店铺不一致；切换店铺后取消旧任务，再重新创建 DRY_RUN。", action: "shop" };
  if (task.state === "PAUSED" && task.currentStep === "MAPPING_INVALID") return { priority: 1, label: "字段映射需要重新确认", detail: "执行前复核发现映射不完整或已变化；补充真实卖家页验证证据后取消旧任务，再新建 DRY_RUN。", action: "mapping" };
  if (task.state === "PAUSED" && ["MAPPING_CHANGED_SINCE_REVIEW", "MAPPING_SNAPSHOT_MISSING"].includes(task.currentStep)) return { priority: 1, label: "字段映射已变化", detail: "任务创建后的映射与当前记录不一致或未冻结；重新逐项核验后取消旧任务，再新建 DRY_RUN。", action: "mapping" };
  if (task.state === "PAUSED" && task.currentStep === "FIELD_VALUE_MISSING") return { priority: 1, label: "商品包缺少字段资料", detail: "执行中发现映射所需来源值缺失；返回商品包补齐可验证资料后取消旧任务，再新建 DRY_RUN。", action: "package" };
  if (task.state === "PAUSED" && task.currentStep === "PAGE_OR_MAPPING_PAUSED") return { priority: 2, label: "页面或字段映射待人工核验", detail: "页面结构或映射定位未能安全执行；查看记录和截图，核验后取消旧任务，再更新真实映射。", action: "mapping" };
  if (task.state === "PAUSED" && task.currentStep === "MANUAL_FIELD_REQUIRED") return { priority: 1, label: "等待人工填写字段", detail: "在卖家页完成当前字段后，确认已人工填写。", action: "acknowledge-manual" };
  if (task.state === "PAUSED" && task.currentStep === "FINAL_REVIEW_REQUIRED") return { priority: 2, label: "等待当前草稿核验", detail: "核对页面、目的地、素材与属性；确认后若有下一条，会回到队列等待再次开始，始终不会发布。", action: "complete-dry-run" };
  if (task.state === "PAUSED") return { priority: 3, label: "任务已暂停", detail: "查看最近记录；非风控暂停须先修复原因、取消旧任务，再新建 DRY_RUN。", action: "detail" };
  if (task.state === "RUNNING") return { priority: 4, label: "正在执行", detail: "持续监测中；如出现风险，任务会自动暂停并保留截图。", action: "detail" };
  if (task.state === "QUEUED") return model.browser.canExecute ? { priority: 5, label: "已排队，可开始", detail: "当前页面身份已核验；开始时会再次复核。", action: "start" } : { priority: 1, label: "先核验当前草稿页的店铺", detail: model.browser.reason || "浏览器连接不代表身份已核验，请先在店铺会话卡完成核对。", action: "identity" };
  if (task.state === "WAITING_FOR_REVIEW") return { priority: 6, label: "等待排队", detail: "资料已通过任务准入，可排队等待执行。", action: "queue" };
  return null;
}
function renderMonitoring() {
  const all = tasks(), taskActions = all.map(task => ({ task, next: monitorAction(task) })).filter(entry => entry.next), packageActions = packageMonitorActions(), actions = [...taskActions, ...packageActions].sort((a, b) => a.next.priority - b.next.priority || String(b.task?.updatedAt || b.job?.reviewedAt || "").localeCompare(String(a.task?.updatedAt || a.job?.reviewedAt || "")));
  const attention = actions.filter(entry => entry.next.priority <= 3).length, review = all.filter(task => task.state === "PAUSED" && task.currentStep === "FINAL_REVIEW_REQUIRED").length, runnable = all.filter(task => ["QUEUED", "WAITING_FOR_REVIEW"].includes(task.state)).length;
  $("#monitorAttention").textContent = attention; $("#monitorReview").textContent = review; $("#monitorRunnable").textContent = runnable;
  const draftable = jobs().filter(job => preflight(job).state === "ready").length, top = actions[0];
  const summary = (top?.job || ["identity", "session-queue"].includes(top?.next.action)) ? `${top.next.label}：${top.next.detail}` : !all.length && draftable ? `已有 ${draftable} 条商品包可创建 DRY_RUN 任务；确认店铺登录后开始逐条草稿填充。` : !all.length ? "还没有 DRY_RUN 任务：先导入商品包并补齐真实审核证据。" : top?.next.priority === 0 ? "优先处理专用 Chrome 中的风控或登录验证，再恢复任务。" : review ? "有草稿等待人工核验；确认无误后结束 DRY_RUN，系统不会发布。" : top?.next.priority <= 2 ? `${top.next.label}：请按下方入口完成资料或映射复核，再重新创建 DRY_RUN 任务。` : runnable ? "已有任务可继续：确认专用 Chrome 登录状态后按队列执行。" : "所有任务当前无待处理动作；继续观察执行记录与页面证据。";
  $("#monitorSummary").textContent = summary; $("#monitorUpdated").textContent = lastStatusAt ? `本地读取 ${eventTime(lastStatusAt)}` : "本地自动刷新";
  const body = $("#monitorActions"); body.replaceChildren();
  if (!actions.length) { const empty = document.createElement("p"); empty.className = "monitor-empty"; empty.textContent = all.length ? "当前没有需要处理的动作。" : draftable ? "商品包已可创建草稿任务；创建后，逐条处理建议会显示在这里。" : "尚无任务。导入并审核商品包后，处理建议会显示在这里。"; body.append(empty); return; }
  for (const { task, job, next } of actions.slice(0, 5)) {
    const card = document.createElement("article"); card.className = `monitor-card priority-${next.priority}`;
    const subject = task ? `${task.id} · ${(task.items || []).map(item => item.destination || item.jobId).join("、") || "无商品"}` : `${job?.destination || "未命名商品包"} · ${job?.locationType === "city" ? "城市链接" : "国家链接"}`;
    card.innerHTML = `<div><span class="monitor-state">${escapeHtml(task?.state || "商品包")}</span><h3>${escapeHtml(next.label)}</h3><p>${escapeHtml(next.detail)}</p><small>${escapeHtml(subject)}</small></div>`;
    const button = document.createElement("button"); button.type = "button"; button.className = next.priority <= 2 ? "primary" : "secondary"; button.textContent = next.action === "identity" ? "核验店铺身份" : next.action === "session-queue" ? "重新排队" : next.action === "detail" ? "查看记录" : next.action === "preview" ? "核对商品包" : next.action === "package" ? "补齐商品包" : next.action === "review" ? "补充审核资料" : next.action === "mapping" ? "核验字段映射" : next.action === "shop" ? "切换商品包店铺" : next.action === "start" ? "开始 DRY_RUN" : next.action === "queue" ? "排队" : next.action === "resume" ? "记录处理后恢复" : next.action === "complete-dry-run" ? "记录草稿核验结论" : "确认已人工填写";
    if (["start", "session-queue"].includes(next.action)) { button.disabled = !model.browser.canExecute; button.title = model.browser.canExecute ? "" : model.browser.reason || "请先核验店铺身份"; }
    button.addEventListener("click", () => runMonitorAction(task, next.action, job)); card.append(button); body.append(card);
  }
}
function taskActionJob(task) {
  const item = (task.items || []).find(entry => entry.state === "PAUSED") || task.items?.[0];
  return jobs().find(job => job.id === item?.jobId);
}
function runMonitorAction(task, action, monitoredJob = null) {
  if (action === "identity") return showIdentityForm();
  if (action === "session-queue") return updateTask(task, "queue");
  const job = monitoredJob || taskActionJob(task);
  if (action === "detail") return openTaskDetail(task);
  if (action === "preview" && job) return openPreview(job);
  if (action === "package" && job) return openPackageCompletion(job);
  if (action === "review" && job) return openReview(job);
  if (action === "mapping" && job) return openMapping(job);
  if (action === "shop") {
    const shop = (model.shops || []).find(candidate => candidate.name === job?.profile?.shop_name);
    if (!shop) { toast("未找到商品包所属店铺；请在“店铺与浏览器”中添加或选择店铺。"); return; }
    $("#shopSelect").value = shop.id;
    return switchShop(shop.id);
  }
  if (["package", "review", "mapping"].includes(action)) { toast("未找到对应商品包，请查看任务记录后重新导入商品包。"); return; }
  if (action === "resume") return openRecovery(task);
  if (action === "complete-dry-run") return openFinalReview(task);
  updateTask(task, action);
}
function openTaskDetail(task) {
  $("#taskDetailTitle").textContent = `${task.id} · 任务详情`;
  $("#taskDetailSummary").textContent = `${task.shopName || task.shopId || "未指定店铺"} · ${task.mode} · 当前状态 ${task.state} · 当前步骤 ${task.currentStep || "—"}`;
  const auditLink = $("#exportTaskAudit"); auditLink.href = `/api/tasks/${encodeURIComponent(task.id)}/export-audit`; auditLink.hidden = false;
  const items = $("#taskItemList"), events = $("#taskEventList"); items.replaceChildren(); events.replaceChildren();
  for (const item of task.items || []) { const node = document.createElement("li"); const completed = (item.completedFields || []).length ? ` · 已完成字段：${item.completedFields.join("、")}` : ""; const pending = item.pendingManualField ? ` · 等待人工：${item.pendingManualField}` : ""; const isolated = item.isolatedReason ? " · 已隔离（原因见事件记录）" : ""; const snapshot = item.mappingSnapshot, reviewed = Array.isArray(snapshot?.fields) ? snapshot.fields.filter(field => field.reviewed).length : 0, mappingInfo = snapshot ? ` · 映射快照：${snapshot.version || "未命名版本"} · 已核验 ${reviewed}/${snapshot.fields.length} 项` : " · 映射快照缺失"; node.innerHTML = `<strong>${escapeHtml(item.destination || item.jobId)}</strong><span>${escapeHtml(item.state || "—")}</span><small>幂等键：${escapeHtml(item.idempotencyKey || "—")}${escapeHtml(mappingInfo)}${item.attempts ? ` · 恢复次数 ${escapeHtml(item.attempts)}` : ""}${escapeHtml(completed)}${escapeHtml(pending)}${escapeHtml(isolated)}</small>`; const href = evidenceHref(item.dryRunEvidence); if (href) { const link = document.createElement("a"); link.href = href; link.target = "_blank"; link.rel = "noopener"; link.textContent = "查看提交前截图"; node.append(link); } items.append(node); }
  if (!(task.items || []).length) items.innerHTML = "<li>没有商品记录。</li>";
  for (const event of task.events || []) { const node = document.createElement("li"); const heading = document.createElement("strong"), detail = document.createElement("span"), time = document.createElement("small"); heading.textContent = event.type || "—"; detail.textContent = event.message || "—"; time.textContent = eventTime(event.at); node.append(heading, detail, time); const href = evidenceHref(event.evidence); if (href) { const link = document.createElement("a"); link.href = href; link.target = "_blank"; link.rel = "noopener"; link.textContent = "打开证据"; node.append(link); } events.append(node); }
  if (!(task.events || []).length) events.innerHTML = "<li>没有事件记录。</li>";
  $("#taskDialog").showModal();
}
function renderImportFeedback() { const box = $("#importFeedback"), details = $("#importDetails"), issues = $("#importIssues"), info = model?.state?.lastImport; if (!info) { box.className = "import-feedback"; box.textContent = "尚未导入商品包。"; details.hidden = true; return; } const skipped = info.skipped?.length || 0, errors = info.errors?.length || 0, staged = info.assetsStaged ? `，已本机暂存 ${info.assetsStaged} 个素材文件` : "", ready = info.acceptedReady ?? info.accepted ?? 0, needsReview = info.acceptedNeedsReview ?? 0, entries = [...(info.skipped || []), ...(info.errors || [])], acceptedText = needsReview ? `${ready} 个已标 READY，${needsReview} 个待审核` : `${ready} 个已标 READY`; box.className = `import-feedback show ${errors ? "error" : skipped ? "warning" : ""}`; box.textContent = `已扫描 ${info.selected} 个商品包：${acceptedText} 并进入工作台${staged}${skipped ? `，${skipped} 个被跳过` : ""}${errors ? `，${errors} 个格式错误` : ""}。待审核商品包只能补齐和核验，不能创建草稿任务。`; details.hidden = entries.length === 0; issues.replaceChildren(...entries.map(item => { const li = document.createElement("li"); const file = item.sourceFile || item.file || item.path || "未命名文件"; const reason = item.reason || item.message || item.error || "未通过当前导入规则"; li.textContent = `${file}：${reason}`; return li; })); details.open = errors > 0; }
function duplicateListingDetail(job) { const listing = job.listing || {}, locationType = listing.location_type || job.locationType, target = String(locationType === "country" ? listing.country : locationType === "city" ? listing.city : "").trim(); if (!target || !["country", "city"].includes(locationType)) return ""; const sameShop = candidate => { const declared = String(candidate.profile?.shop_name || "").trim(); return !declared || declared === model.activeShop?.name; }; const duplicates = jobs().filter(candidate => candidate.id !== job.id && sameShop(candidate) && (candidate.listing?.location_type || candidate.locationType) === locationType && String(locationType === "country" ? candidate.listing?.country : candidate.listing?.city || "").trim() === target); if (!duplicates.length) return ""; const label = locationType === "country" ? "国家" : "城市"; return `同店已有 ${label}级“${target}”商品包：${duplicates.map(candidate => String(candidate.sourceFile || candidate.id).split(/[\\/]/).pop()).join("、")}。请保留一条并重新导入。`; }
function preflight(job) { if (!jobMatchesCurrentStore(job)) return { state: "blocked", label: "店铺不匹配", detail: `请切换至 ${job.profile.shop_name} 后处理` }; if (job.status !== "READY") return { state: "blocked", label: "待确认商品包", detail: `当前状态为 ${job.status || "UNKNOWN"}；填入真实资料、完成页面核验后改为 READY，才能创建草稿任务` }; const duplicateDetail = duplicateListingDetail(job); if (duplicateDetail) return { state: "blocked", label: "同店重复商品", detail: duplicateDetail }; if (!job.packageValidation?.valid) return { state: "blocked", label: "商品包待修复", detail: (job.packageValidation?.issues || ["请重新导入完整商品包"]).join("、") }; const blockers = job.releaseBlockers || []; if (blockers.length) return { state: "blocked", label: `发布阻塞 ${blockers.length} 项`, detail: blockers.join("、") }; if (!job.mappingValidation?.valid) return { state: "blocked", label: "字段映射未就绪", detail: (job.mappingValidation?.issues || ["请重新导入包含 automation_mapping 的商品包"]).join("、") }; return { state: "ready", label: "可创建草稿任务", detail: "已通过商品包、证据与 DRY_RUN 映射检查" }; }
function renderQueueFilters() { const all = jobs(), ready = all.filter(job => preflight(job).state === "ready").length, blocked = all.length - ready; document.querySelectorAll("[data-queue-filter]").forEach(button => { const type = button.dataset.queueFilter; button.classList.toggle("is-active", type === queueFilter); button.setAttribute("aria-pressed", String(type === queueFilter)); button.textContent = type === "all" ? `全部 ${all.length}` : type === "ready" ? `可建草稿 ${ready}` : `发布阻塞 ${blocked}`; }); }
function renderJobs() {
  const body = $("#jobs"), rows = filteredJobs(); body.replaceChildren(); const readyRows = rows.filter(job => preflight(job).state === "ready"); $("#queueState").textContent = jobs().length ? `当前显示 ${rows.length} / ${jobs().length} 条商品包；选择最多 10 条，核验类目、价格与履约后进入草稿填充。` : "导入后，这里会显示可处理的商品链接。";
  if (!rows.length) { body.innerHTML = `<tr><td colspan="6" class="empty-state">${jobs().length ? "没有匹配的商品包，试试清空搜索。" : "先导入商品包，再开始批量上架。"}</td></tr>`; $("#selectAll").checked = false; $("#selectAll").indeterminate = false; renderBulkBar(); return; }
  const tpl = $("#rowTemplate"); for (const job of rows) { const node = tpl.content.cloneNode(true), p = job.profile || {}, check = node.querySelector(".job-check"), test = preflight(job); check.checked = selectedIds.has(job.id); check.disabled = test.state !== "ready"; check.setAttribute("aria-label", `选择 ${job.destination} 商品包`); check.addEventListener("change", () => { check.checked ? selectedIds.add(job.id) : selectedIds.delete(job.id); renderMetrics(); renderJobs(); }); node.querySelector(".destination").textContent = job.destination; node.querySelector(".location-type").textContent = job.locationType === "country" ? "国家链接" : "城市链接"; node.querySelector(".title").textContent = job.title; node.querySelector(".source-file").textContent = String(job.sourceFile || "").split(/[\\/]/).pop() || "未命名商品包"; node.querySelector(".main-image").textContent = job.mainImage ? "已匹配" : "缺失"; node.querySelector(".detail-images").textContent = `${job.detailImageCount} 张`; node.querySelector(".shop-name").textContent = p.shop_name || "未指定店铺"; node.querySelector(".price-stock").textContent = `¥${p.price_cny ?? "—"} · 库存 ${p.inventory ?? "—"}`; node.querySelector(".category-path").textContent = p.category_path || "未指定类目"; const chip = node.querySelector(".status-chip"); chip.textContent = test.label; chip.classList.add(test.state); node.querySelector(".status-detail").textContent = test.detail; const action = node.querySelector(".open-job"); action.textContent = "审核资料"; action.addEventListener("click", () => openReview(job)); node.querySelector(".preview-job").addEventListener("click", () => openPreview(job)); node.querySelector(".complete-package").addEventListener("click", () => openPackageCompletion(job)); body.append(node); }
  const readyIds = readyRows.map(job => job.id), selectedReady = readyIds.filter(id => selectedIds.has(id)); $("#selectAll").checked = readyIds.length > 0 && selectedReady.length === readyIds.length; $("#selectAll").indeterminate = selectedReady.length > 0 && selectedReady.length < readyIds.length; renderBulkBar();
}
function renderBulkBar() { const count = [...selectedIds].filter(id => jobs().some(job => job.id === id && preflight(job).state === "ready")).length; $("#bulkBar").hidden = count === 0; $("#bulkCount").textContent = count; $("#prepareSelected").disabled = count === 0; }
function renderAll() { renderShops(); setBrowser(model.browser, model.chromeInstalled); renderMetrics(); renderImportFeedback(); renderQueueFilters(); renderJobs(); renderTasks(); renderMonitoring(); }
function exportPreflightReport() { window.location.assign("/api/reports/preflight"); log("已请求导出本机审核清单；报告不含账号、Cookie、素材绝对路径或淘宝发布结果。"); toast("正在下载本机审核清单"); }
async function refresh({ quiet = false } = {}) { try { model = await api("/api/status"); lastStatusAt = new Date().toISOString(); selectedIds = new Set([...selectedIds].filter(id => jobs().some(job => job.id === id))); renderAll(); if (!quiet) { log("状态已刷新。"); toast("工作台状态已更新"); } } catch (error) { log(`状态读取失败：${error.message}`); toast(`状态读取失败：${error.message}`); } }
async function launchChrome() { try { const data = await api("/api/chrome/launch", { method: "POST", body: "{}" }); log(data.alreadyRunning ? `${data.shop.name} 的专用 Chrome 已在运行。` : `已启动 ${data.shop.name} 的专用 Chrome。`); toast(data.alreadyRunning ? "已复用当前店铺会话" : "专用 Chrome 已启动，请在窗口中登录"); setTimeout(() => refresh({ quiet: true }), 1100); } catch (error) { log(`无法启动 Chrome：${error.message}`); toast(`无法启动 Chrome：${error.message}`); } }
async function openSeller() { try { await api("/api/chrome/open-seller", { method: "POST", body: "{}" }); log(`${model.activeShop.name} 的千牛后台已打开。`); toast("千牛后台已在专用 Chrome 打开"); } catch (error) { log(`打开后台失败：${error.message}`); toast(`打开后台失败：${error.message}`); } }
async function importFolderPath() { const folderPath = $("#folderPath").value.trim(); if (!folderPath) { toast("请粘贴商品包文件夹路径，或直接选择文件。 "); $("#folderPath").focus(); return; } try { updateSaveState("正在同步目录…"); const data = await api("/api/jobs/import", { method: "POST", body: JSON.stringify({ folderPath }) }), info = data.state.lastImport, summary = `${info.acceptedReady ?? info.accepted ?? 0} 个 READY${info.acceptedNeedsReview ? `，${info.acceptedNeedsReview} 个待审核` : ""}`; model.state = data.state; selectedIds.clear(); renderMetrics(); renderImportFeedback(); renderJobs(); updateSaveState(); log(`目录同步完成：${summary} 商品包进入工作台。`); toast(`已导入 ${summary} 商品包`); } catch (error) { updateSaveState(); log(`同步目录失败：${error.message}`); toast(`同步失败：${error.message}`); } }
function isImageAsset(file) { return [".png", ".jpg", ".jpeg", ".webp"].some(extension => file.name.toLowerCase().endsWith(extension)); }
function fileBase64(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error(`无法读取素材：${file.name}`)); reader.onload = () => resolve(String(reader.result || "").split(",", 2)[1] || ""); reader.readAsDataURL(file); }); }
async function importFiles(fileList) { const selected = [...fileList], files = selected.filter(file => file.name.toLowerCase().endsWith(".json")), assets = selected.filter(isImageAsset); if (!files.length) { toast("未找到 JSON 商品包文件。 "); return; } if (files.length > 300 || assets.length > 1200) { toast("一次最多选择 300 个商品包和 1200 个素材文件，请分批导入。 "); return; } try { const packages = await Promise.all(files.map(async file => ({ sourceFile: file.webkitRelativePath || file.name, content: await file.text() }))); const shouldStage = assets.length > 0 || selected.some(file => file.webkitRelativePath); updateSaveState(shouldStage ? "正在暂存商品包与素材…" : "正在校验商品包…"); const payload = shouldStage ? { packages, assets: await Promise.all(assets.map(async file => ({ sourceFile: file.webkitRelativePath || file.name, contentBase64: await fileBase64(file) }))) } : { packages }; const data = await api(shouldStage ? "/api/jobs/import-bundle" : "/api/jobs/import-files", { method: "POST", body: JSON.stringify(payload) }), info = data.state.lastImport; model.state = data.state; selectedIds.clear(); renderMetrics(); renderImportFeedback(); renderJobs(); updateSaveState(); const staged = info.assetsStaged ? `，已暂存 ${info.assetsStaged} 个素材文件` : "", summary = `${info.acceptedReady ?? info.accepted ?? 0} 个 READY${info.acceptedNeedsReview ? `，${info.acceptedNeedsReview} 个待审核` : ""}`; log(`文件导入完成：${summary} 商品包进入工作台${staged}。`); toast(`导入完成：${summary} 商品包${staged}`); } catch (error) { updateSaveState(); log(`文件导入失败：${error.message}`); toast(`导入失败：${error.message}`); } }
function evidenceText(value) { return typeof value === "string" ? value : value?.source || value?.reference || value?.url || ""; }
function openPreview(job) {
  const profile = job.profile || {}, variants = titleVersions(job), detailImages = job.assets?.detail_images, preflightResult = preflight(job);
  $("#previewTitle").textContent = `${job.destination} · 商品包预览`;
  $("#previewSummary").textContent = preflightResult.state === "ready" ? "商品包已通过当前准入检查；仍只允许进入 DRY_RUN。" : `当前不能创建草稿任务：${preflightResult.detail}`;
  $("#previewState").textContent = preflightResult.label; $("#previewState").className = `status-chip ${preflightResult.state}`;
  $("#previewCore").innerHTML = `<div><span>目的地</span><strong>${escapeHtml(job.destination || "未提供")}</strong><small>${escapeHtml(job.locationType === "country" ? "国家链接" : job.locationType === "city" ? "城市链接" : "类型待确认")}</small></div><div><span>店铺</span><strong>${escapeHtml(profile.shop_name || "未指定")}</strong><small>商品包内记录</small></div><div><span>标题字数</span><strong>${escapeHtml(job.titleUnits ?? "待核验")}</strong><small>使用前仍须按真实类目复核</small></div>`;
  const selectedIndex = job.listing?.selected_title_index; const titles = $("#previewTitles"); titles.replaceChildren(...variants.map((title, index) => { const row = document.createElement("li"); row.innerHTML = `<span>标题 ${index + 1}${selectedIndex === index ? " · 已选" : ""}</span><strong>${escapeHtml(title)}</strong>`; return row; }));
  if (!job.packageValidation?.valid) { const note = document.createElement("p"); note.className = "preview-warning"; note.textContent = `商品包待修复：${(job.packageValidation?.issues || ["请重新导入完整商品包"]).join("；")}。`; titles.append(note); }
  const assetRows = Array.isArray(detailImages) && detailImages.length ? detailImages.map((file, index) => `<li><span>${index + 1}</span>${escapeHtml(sourceName(file))}</li>`).join("") : job.detailImageCount ? `<li class="asset-order-missing"><span>?</span>当前本机记录仅有 ${escapeHtml(job.detailImageCount)} 张详情图数量，未保存顺序；重新导入商品包后可核验顺序。</li>` : "<li>未提供详情图</li>";
  $("#previewAssets").innerHTML = `<div class="asset-preview-main"><span>主图</span><strong>${escapeHtml(sourceName(job.mainImage))}</strong><small>${job.mainImage ? "已提供，仍待目的地一致性审核" : "未提供"}</small></div><ol>${assetRows}</ol>`;
  const profileRows = [["类目", profile.category_path || "未提供"], ["价格", profile.price_cny === undefined ? "未提供" : `¥${profile.price_cny}`], ["库存", profile.inventory ?? "未提供"], ["履约", [profile.delivery_method, profile.freight_template, profile.ship_within_hours ? `${profile.ship_within_hours} 小时内` : ""].filter(Boolean).join(" · ") || "未提供"]];
  $("#previewProfile").innerHTML = profileRows.map(([label, value]) => `<dt>${escapeHtml(label)}</dt><dd>${escapeHtml(value)}<small>商品包内声明，待人工验证</small></dd>`).join("");
  $("#previewEvidence").replaceChildren(...reviewFields.map(([key, label]) => { const row = document.createElement("li"), value = evidenceText(job.reviewEvidence?.[key]); row.className = value ? "confirmed" : "missing"; row.innerHTML = `<strong>${escapeHtml(label)}</strong><span>${value ? "已记录来源" : "待补充"}</span>`; return row; }));
  $("#previewChecks").replaceChildren(...(job.checks || []).map(check => { const row = document.createElement("li"); row.className = check.passed ? "confirmed" : "missing"; row.textContent = `${check.passed ? "通过" : "未通过"} · ${check.name || "未命名检查"}`; return row; }));
  $("#previewToReview").onclick = () => { $("#previewDialog").close(); openReview(job); };
  $("#previewDialog").showModal();
}
function openPackageCompletion(job) {
  const completion = job.packageCompletion || {}, variants = completion.titleVersions || titleVersions(job), secondary = completion.secondaryImages || job.assets?.secondary_images || [];
  $("#packageCompletionJobId").value = job.id; $("#packageCompletionTitle").textContent = `${job.destination} · 补齐商品包`;
  $("#packageCompletionSummary").textContent = job.packageValidation?.valid ? "商品包字段已齐全；可在这里核对或更新本机补充记录。" : `当前需要补齐：${(job.packageValidation?.issues || []).join("、")}`;
  $("#completionTitle1").value = variants[0] || ""; $("#completionTitle2").value = variants[1] || "";
  $("#completionSelectedTitle").value = Number.isInteger(completion.selectedTitleIndex) ? String(completion.selectedTitleIndex) : Number.isInteger(job.listing?.selected_title_index) ? String(job.listing.selected_title_index) : "";
  for (let index = 0; index < 4; index += 1) $(`#completionImage${index + 1}`).value = secondary[index] || "";
  const canExport = Boolean(job.packageCompletion) && /^(?:[A-Za-z]:[\\/]|\/)/.test(String(job.sourceFile || "")); const exportLink = $("#exportCompletedPackage"); exportLink.hidden = !canExport; exportLink.href = canExport ? `/api/jobs/${encodeURIComponent(job.id)}/export-package` : "#";
  $("#resetPackageCompletion").hidden = !job.packageCompletion; $("#packageCompletionError").textContent = ""; $("#packageCompletionDialog").showModal();
}
async function savePackageCompletion(event) {
  event.preventDefault(); const id = $("#packageCompletionJobId").value;
  const packageCompletion = { titleVersions: [$("#completionTitle1").value.trim(), $("#completionTitle2").value.trim()], selectedTitleIndex: $("#completionSelectedTitle").value, secondaryImages: [1, 2, 3, 4].map(index => $(`#completionImage${index}`).value.trim()) };
  try { const data = await api(`/api/jobs/${encodeURIComponent(id)}/package-completion`, { method: "POST", body: JSON.stringify({ packageCompletion }) }); model.state = data.state; $("#packageCompletionDialog").close(); renderAll(); log(`${data.job.destination}：已保存本机商品包补充记录，${data.job.packageValidation.valid ? "商品包字段已齐全" : `仍缺 ${data.job.packageValidation.issues.length} 项`}。`); toast(data.job.packageValidation.valid ? "商品包字段已齐全，继续补充审核资料" : `已保存；仍有 ${data.job.packageValidation.issues.length} 项待补齐`); } catch (error) { $("#packageCompletionError").textContent = error.message; }
}
async function resetPackageCompletion() {
  const id = $("#packageCompletionJobId").value; try { const data = await api(`/api/jobs/${encodeURIComponent(id)}/package-completion`, { method: "POST", body: JSON.stringify({ reset: true }) }); model.state = data.state; $("#packageCompletionDialog").close(); renderAll(); log(`${data.job.destination}：已撤销本机商品包补充记录。`); toast("已恢复原始商品包数据"); } catch (error) { $("#packageCompletionError").textContent = error.message; }
}
function openReview(job) { $("#reviewJobId").value = job.id; $("#reviewTitle").textContent = `${job.destination} · 审核资料`; const mappingNote = job.mappingValidation?.valid ? "字段映射结构已就绪。" : `字段映射尚未就绪：${(job.mappingValidation?.issues || ["请重新导入含 automation_mapping 的商品包"]).join("、")}。`; $("#reviewSummary").textContent = job.releaseBlockers?.length ? `当前仍有 ${job.releaseBlockers.length} 项发布阻塞。请填写每项证据的文件路径、后台截图编号或可复核链接。${mappingNote}` : `五项证据齐全；${mappingNote}`; for (const [key] of reviewFields) $(`#review-${key}`).value = evidenceText(job.reviewEvidence?.[key]); $("#reviewError").textContent = ""; $("#reviewDialog").showModal(); }
async function saveReview(event) { event.preventDefault(); const id = $("#reviewJobId").value; const reviewEvidence = Object.fromEntries(reviewFields.map(([key]) => [key, $(`#review-${key}`).value])); try { const data = await api(`/api/jobs/${encodeURIComponent(id)}/review-evidence`, { method: "POST", body: JSON.stringify({ reviewEvidence }) }); model.state = data.state; selectedIds = new Set([...selectedIds].filter(selectedId => jobs().some(job => job.id === selectedId && preflight(job).state === "ready"))); $("#reviewDialog").close(); renderAll(); log(`${data.job.destination}：审核证据已保存，${data.job.releaseBlockers.length ? `仍缺 ${data.job.releaseBlockers.length} 项` : "可创建 DRY_RUN 草稿任务"}。`); toast(data.job.releaseBlockers.length ? `已保存；仍缺 ${data.job.releaseBlockers.length} 项证据` : "证据已齐全，可创建 DRY_RUN 草稿任务"); } catch (error) { $("#reviewError").textContent = error.message; } }
const mappingChecklistFields = [["category", "类目"], ["title", "标题"], ["price", "价格"], ["main_images", "主图"], ["secondary_images", "4 张副图"], ["detail_images", "详情图"]];
function mappingTemplate() { return { platform: "taobao", version: "", verified_evidence: "", draft_url: "", fields: [{ id: "category", source: "profile.category_path", locator: { strategy: "label", value: "" }, interaction: "manual", reviewed: false }, { id: "title", source: "listing.title", locator: { strategy: "label", value: "" }, interaction: "fill", reviewed: false }, { id: "price", source: "profile.price_cny", locator: { strategy: "label", value: "" }, interaction: "fill", reviewed: false }, { id: "main_images", source: "assets.main_image", locator: { strategy: "css", value: "" }, interaction: "upload", reviewed: false }, { id: "secondary_images", source: "assets.secondary_images", locator: { strategy: "css", value: "" }, interaction: "upload", reviewed: false }, { id: "detail_images", source: "assets.detail_images", locator: { strategy: "css", value: "" }, interaction: "upload", reviewed: false }] }; }
function mappingDraft() { try { const value = JSON.parse($("#mappingJson").value); return value && typeof value === "object" && !Array.isArray(value) ? value : null; } catch { return null; } }
function mappingFieldReady(field) { const locator = field?.locator || {}; return Boolean(String(locator.strategy || "").trim() && String(locator.value || "").trim() && (locator.strategy !== "role" || String(locator.role || "").trim()) && ["fill", "select", "upload", "manual"].includes(field.interaction)); }
function renderMappingChecklist() { const host = $("#mappingChecklist"); host.replaceChildren(); const mapping = mappingDraft(); if (!mapping || !Array.isArray(mapping.fields)) { const note = document.createElement("p"); note.className = "dialog-help"; note.textContent = "映射 JSON 无法解析，暂时不能核验字段。"; host.append(note); return; } const fields = new Map(mapping.fields.filter(field => field?.id).map(field => [field.id, field])); for (const [id, label] of mappingChecklistFields) { const field = fields.get(id), ready = mappingFieldReady(field), reviewed = field?.reviewed === true, manual = field?.interaction === "manual"; const row = document.createElement("label"), checkbox = document.createElement("input"), copy = document.createElement("span"), name = document.createElement("strong"), detail = document.createElement("small"), state = document.createElement("span"); row.className = `mapping-check-item${reviewed ? " reviewed" : manual ? " manual" : !ready ? " blocked" : ""}`; checkbox.type = "checkbox"; checkbox.checked = reviewed; checkbox.disabled = !ready; checkbox.setAttribute("aria-label", `标记${label}已在当前卖家页核验`); name.textContent = label; if (!field) { detail.textContent = "未添加字段"; state.textContent = "待补"; } else if (!ready) { detail.textContent = "需补定位器或交互方式"; state.textContent = "待补"; } else if (reviewed) { detail.textContent = manual ? "人工填写，已确认" : "定位器已确认"; state.textContent = "已核验"; } else { detail.textContent = manual ? "需人工填写后确认" : "已录入，待核验"; state.textContent = manual ? "人工填写" : "待核验"; } copy.className = "mapping-check-copy"; state.className = "mapping-check-state"; copy.append(name, detail); row.append(checkbox, copy, state); checkbox.addEventListener("change", () => { const next = mappingDraft(); const target = next?.fields?.find(candidate => candidate.id === id); if (!target) return; target.reviewed = checkbox.checked; $("#mappingJson").value = JSON.stringify(next, null, 2); $("#mappingError").textContent = ""; renderMappingChecklist(); }); host.append(row); } }
function setMappingCaptureStatus(message, risk = false) { const status = $("#mappingCaptureStatus"); status.textContent = message; status.classList.toggle("is-risk", risk); }
function renderMappingCaptureHistory(job) { const host = $("#mappingCaptureHistory"); host.replaceChildren(); const captures = Array.isArray(job?.mappingCaptures) ? job.mappingCaptures.slice(0, 3) : []; for (const capture of captures) { const row = document.createElement("article"), copy = document.createElement("div"), title = document.createElement("strong"), detail = document.createElement("small"); row.className = `mapping-capture-record${capture.risk ? " risk" : ""}`; title.textContent = capture.risk ? `已记录风险现场：${capture.risk}` : "已记录卖家页证据"; detail.textContent = `${eventTime(capture.capturedAt)} · 仅供人工核验`; copy.append(title, detail); row.append(copy); const href = evidenceHref(capture.evidence); if (href) { const link = document.createElement("a"); link.href = href; link.target = "_blank"; link.rel = "noopener"; link.textContent = "查看截图"; row.append(link); } host.append(row); } }
function openMapping(job) { if (!job) return; $("#mappingJobId").value = job.id; $("#mappingTitle").textContent = `${job.destination} · 字段映射`; const mapping = Object.keys(job.automationMapping || {}).length ? job.automationMapping : mappingTemplate(); $("#mappingJson").value = JSON.stringify(mapping, null, 2); $("#mappingError").textContent = ""; renderMappingCaptureHistory(job); renderMappingChecklist(); setMappingCaptureStatus("尚未记录页面证据。请先在专用 Chrome 手动打开正确的卖家草稿页。"); if ($("#reviewDialog").open) $("#reviewDialog").close(); $("#mappingDialog").showModal(); }
async function captureMappingPage() { const id = $("#mappingJobId").value, button = $("#captureMappingPage"); if (!id) { setMappingCaptureStatus("未找到当前商品包，请关闭窗口后重试。", true); return; } button.disabled = true; setMappingCaptureStatus("正在记录当前专用 Chrome 页面…"); try { const data = await api(`/api/jobs/${encodeURIComponent(id)}/capture-mapping-evidence`, { method: "POST", body: "{}" }), capture = data.capture; model.state = data.state; renderMappingCaptureHistory(data.job); if (capture.risk) { setMappingCaptureStatus(`已保存现场截图，但检测到“${capture.risk}”。请在专用 Chrome 手动完成验证后重新记录；本次不会写入映射。`, true); return; } let mapping; try { mapping = JSON.parse($("#mappingJson").value); } catch { mapping = mappingTemplate(); } const insertedUrl = !String(mapping.draft_url || "").trim(), insertedEvidence = !String(mapping.verified_evidence || "").trim(); if (insertedUrl) mapping.draft_url = capture.url; if (insertedEvidence) mapping.verified_evidence = capture.evidence; $("#mappingJson").value = JSON.stringify(mapping, null, 2); renderMappingChecklist(); setMappingCaptureStatus(`已保存本地页面截图；${insertedUrl || insertedEvidence ? "已填入空白的草稿页地址或证据字段" : "现有映射内容已保留"}。请继续人工核验每个定位器。`); } catch (error) { setMappingCaptureStatus(error.message, true); } finally { button.disabled = false; } }
async function saveMapping(event) { event.preventDefault(); const id = $("#mappingJobId").value; let automationMapping; try { automationMapping = JSON.parse($("#mappingJson").value); } catch { $("#mappingError").textContent = "映射 JSON 无法解析。"; return; } try { const data = await api(`/api/jobs/${encodeURIComponent(id)}/automation-mapping`, { method: "POST", body: JSON.stringify({ automationMapping }) }); model.state = data.state; $("#mappingDialog").close(); renderAll(); const status = data.job.mappingValidation?.valid ? "结构校验通过；仍需审核其余发布证据" : `已保存，仍有 ${data.job.mappingValidation?.issues?.length || 0} 项映射问题`; log(`${data.job.destination}：字段映射${status}。`); toast(status); } catch (error) { $("#mappingError").textContent = error.message; } }
async function openJob(job) { try { const data = await api(`/api/jobs/${encodeURIComponent(job.id)}/open-seller`, { method: "POST", body: "{}" }); model.state = data.state; renderJobs(); log(`${job.destination}：上架页已在 ${model.activeShop.name} 的专用 Chrome 打开。`); toast(`${job.destination} 上架页已打开`); } catch (error) { log(`${job.destination} 无法打开：${error.message}`); toast(`${job.destination} 无法打开：${error.message}`); } }
async function switchShop(shopId = $("#shopSelect").value) { try { const data = await api("/api/shops/select", { method: "POST", body: JSON.stringify({ shopId }) }); model.state = data.state; model.activeShop = data.activeShop; model.browser = data.browser; $("#shopSelect").value = data.activeShop.id; selectedIds.clear(); renderAll(); log(`已切换到 ${data.activeShop.name}。`); toast(`已切换至 ${data.activeShop.name}`); } catch (error) { log(`店铺切换失败：${error.message}`); toast(`店铺切换失败：${error.message}`); } }
async function addShop(event) { event.preventDefault(); $("#shopError").textContent = ""; try { const data = await api("/api/shops", { method: "POST", body: JSON.stringify({ name: $("#shopName").value, loginHint: $("#loginHint").value }) }); await api("/api/shops/select", { method: "POST", body: JSON.stringify({ shopId: data.shop.id }) }); $("#shopDialog").close(); $("#shopForm").reset(); log(`已添加 ${data.shop.name}，请启动其专用 Chrome 后在淘宝页面登录。`); toast(`已添加 ${data.shop.name}`); await refresh({ quiet: true }); } catch (error) { $("#shopError").textContent = error.message; } }
function selectReady() { const batch = filteredJobs().filter(job => preflight(job).state === "ready").slice(0, 10); selectedIds = new Set(batch.map(job => job.id)); renderMetrics(); renderJobs(); toast(`已选择本页前 ${batch.length} 条可创建草稿任务的链接`); }
function clearSelected() { selectedIds.clear(); renderMetrics(); renderJobs(); }
function reviewSelected() { const selected = jobs().filter(job => selectedIds.has(job.id)); const blocked = selected.filter(job => preflight(job).state !== "ready"); const message = blocked.length ? `${blocked.length} 条仍有阻塞项，请检查店铺与商品包。` : `${selected.length} 条均可进入下一步。`; log(`批量预检：${message}`); toast(message); }
async function prepareSelected() { const jobIds = jobs().filter(job => selectedIds.has(job.id) && preflight(job).state === "ready").map(job => job.id); if (!jobIds.length) { toast("请先选择可创建草稿任务的商品包。"); return; } try { const data = await api("/api/tasks", { method: "POST", body: JSON.stringify({ jobIds, mode: "DRY_RUN" }) }); model.state = data.state; selectedIds.clear(); renderAll(); log(`已创建 ${data.task.id}：${data.task.items.length} 条 DRY_RUN 任务，尚未打开淘宝页面。`); toast(`已创建 DRY_RUN 任务：${data.task.items.length} 条`); } catch (error) { log(`无法创建任务：${error.message}`); toast(`无法创建任务：${error.message}`); } }
async function updateTask(task, action, reason = "") { if ((action === "start" || (action === "queue" && task.currentStep === "SESSION_REVALIDATION_FAILED")) && !model.browser.canExecute) { toast(model.browser.reason || "请先核验当前草稿页的店铺身份。"); showIdentityForm(); return; } try { const data = await api(`/api/tasks/${encodeURIComponent(task.id)}/${action}`, { method: "POST", body: JSON.stringify({ reason }) }); model.state = data.state; if (data.browser) model.browser = data.browser; renderAll(); const labels = { queue: "已排队", start: "已开始执行前复核", pause: "已暂停", resume: "已恢复排队", "acknowledge-manual": "已记录人工填写", "complete-dry-run": data.task?.state === "COMPLETED" ? "本批 DRY_RUN 已人工核验" : "当前草稿已核验，等待下一条", "isolate-item": data.task?.state === "COMPLETED_WITH_ISOLATIONS" ? "已隔离当前商品，本批结束" : "已隔离当前商品，剩余条目待手动开始", cancel: "已取消" }, label = labels[action] || "已更新"; log(`${task.id} ${label}。${action === "pause" ? "未尝试处理滑块、验证码或风控。" : ""}`); toast(`${task.id} ${label}`); if (["start", "queue", "resume", "acknowledge-manual", "complete-dry-run"].includes(action)) await refresh({ quiet: true }); } catch (error) { log(`任务操作失败：${error.message}`); toast(`任务操作失败：${error.message}`); await refresh({ quiet: true }); } }
function openRisk(task) { $("#riskTaskId").value = task.id; $("#riskReason").selectedIndex = 0; $("#riskEvidence").value = ""; $("#riskError").textContent = ""; $("#riskDialog").showModal(); }
async function saveRisk(event) { event.preventDefault(); const task = { id: $("#riskTaskId").value }; try { const data = await api(`/api/tasks/${encodeURIComponent(task.id)}/pause`, { method: "POST", body: JSON.stringify({ reason: $("#riskReason").value, evidence: $("#riskEvidence").value }) }); model.state = data.state; $("#riskDialog").close(); renderAll(); log(`${task.id} 已因风控暂停；未尝试处理滑块、验证码或风控。`); toast(`${task.id} 已暂停，等待人工处理`); } catch (error) { $("#riskError").textContent = error.message; } }
function openRecovery(task) { $("#recoveryTaskId").value = task.id; $("#recoveryReason").value = ""; $("#recoveryEvidence").value = ""; $("#recoveryError").textContent = ""; $("#recoveryDialog").showModal(); }
async function saveRecovery(event) { event.preventDefault(); const task = { id: $("#recoveryTaskId").value }, reason = $("#recoveryReason").value.trim(), evidence = $("#recoveryEvidence").value.trim(); if (!reason) { $("#recoveryError").textContent = "请填写人工处理结果。"; return; } try { const data = await api(`/api/tasks/${encodeURIComponent(task.id)}/resume`, { method: "POST", body: JSON.stringify({ reason, evidence }) }); model.state = data.state; $("#recoveryDialog").close(); renderAll(); log(`${task.id} 已记录人工处理结果并恢复排队；未绕过滑块、验证码或风控。`); toast(`${task.id} 已恢复排队`); await refresh({ quiet: true }); } catch (error) { $("#recoveryError").textContent = error.message; } }
function openFinalReview(task) { $("#finalReviewTaskId").value = task.id; $("#finalReviewReason").value = ""; $("#finalReviewEvidence").value = ""; $("#finalReviewError").textContent = ""; $("#finalReviewDialog").showModal(); }
async function saveFinalReview(event) { event.preventDefault(); const task = { id: $("#finalReviewTaskId").value }, reason = $("#finalReviewReason").value.trim(), evidence = $("#finalReviewEvidence").value.trim(); if (!reason) { $("#finalReviewError").textContent = "请填写草稿核验结论。"; return; } try { const data = await api(`/api/tasks/${encodeURIComponent(task.id)}/complete-dry-run`, { method: "POST", body: JSON.stringify({ reason, evidence }) }); model.state = data.state; $("#finalReviewDialog").close(); renderAll(); const label = data.task?.state === "COMPLETED" ? "本批 DRY_RUN 已记录人工核验结论" : "当前草稿已记录核验结论，等待下一条"; log(`${task.id} ${label}；未点击发布或提交。`); toast(`${task.id} ${label}`); await refresh({ quiet: true }); } catch (error) { $("#finalReviewError").textContent = error.message; } }
function openIsolation(task) { $("#isolateTaskId").value = task.id; $("#isolateReason").value = ""; $("#isolateError").textContent = ""; $("#isolateSummary").textContent = `${task.id} 当前为“${task.currentStep}”。隔离仅跳过本条非风控资料问题；剩余商品仍需你再次手动开始 DRY_RUN。不会打开卖家页、提交或发布。`; $("#isolateDialog").showModal(); }
async function saveIsolation(event) { event.preventDefault(); const task = { id: $("#isolateTaskId").value }, reason = $("#isolateReason").value.trim(); if (!reason) { $("#isolateError").textContent = "请填写隔离原因。"; return; } try { const data = await api(`/api/tasks/${encodeURIComponent(task.id)}/isolate-item`, { method: "POST", body: JSON.stringify({ reason }) }); model.state = data.state; $("#isolateDialog").close(); renderAll(); log(`${task.id} 已隔离当前非风控商品；未打开卖家页面、未提交或发布。`); toast(`${task.id} 已隔离当前商品`); } catch (error) { $("#isolateError").textContent = error.message; } }

$("#identityForm").addEventListener("submit", confirmIdentity);
$("#refresh").addEventListener("click", refresh); $("#launchChrome").addEventListener("click", launchChrome); $("#openSeller").addEventListener("click", openSeller); $("#importJobs").addEventListener("click", importFolderPath); $("#shopSelect").addEventListener("change", switchShop); $("#searchJobs").addEventListener("input", event => { query = event.target.value; renderJobs(); }); document.querySelectorAll("[data-queue-filter]").forEach(button => button.addEventListener("click", () => { queueFilter = button.dataset.queueFilter; selectedIds.clear(); renderQueueFilters(); renderJobs(); })); $("#selectReady").addEventListener("click", selectReady); $("#clearSelected").addEventListener("click", clearSelected); $("#reviewSelected").addEventListener("click", reviewSelected); $("#prepareSelected").addEventListener("click", prepareSelected); $("#selectAll").addEventListener("change", event => { for (const job of filteredJobs()) if (preflight(job).state === "ready") event.target.checked ? selectedIds.add(job.id) : selectedIds.delete(job.id); renderMetrics(); renderJobs(); });
$("#chooseFiles").addEventListener("click", () => $("#packageFiles").click()); $("#chooseFolder").addEventListener("click", () => $("#packageFolder").click()); $("#packageFiles").addEventListener("change", event => importFiles(event.target.files)); $("#packageFolder").addEventListener("change", event => importFiles(event.target.files)); $("#dropZone").addEventListener("click", () => $("#packageFiles").click()); $("#dropZone").addEventListener("keydown", event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); $("#packageFiles").click(); } }); $("#dropZone").addEventListener("dragover", event => { event.preventDefault(); $("#dropZone").classList.add("dragover"); }); $("#dropZone").addEventListener("dragleave", () => $("#dropZone").classList.remove("dragover")); $("#dropZone").addEventListener("drop", event => { event.preventDefault(); $("#dropZone").classList.remove("dragover"); importFiles(event.dataTransfer.files); });
$("#addShop").addEventListener("click", () => $("#shopDialog").showModal()); $("#addShopTop").addEventListener("click", () => $("#shopDialog").showModal()); $("#closeShopDialog").addEventListener("click", () => $("#shopDialog").close()); $("#cancelShop").addEventListener("click", () => $("#shopDialog").close()); $("#shopForm").addEventListener("submit", addShop); refresh({ quiet: true });
$("#reviewForm").addEventListener("submit", saveReview); $("#closeReviewDialog").addEventListener("click", () => $("#reviewDialog").close()); $("#cancelReview").addEventListener("click", () => $("#reviewDialog").close());
$("#packageCompletionForm").addEventListener("submit", savePackageCompletion); $("#closePackageCompletionDialog").addEventListener("click", () => $("#packageCompletionDialog").close()); $("#cancelPackageCompletion").addEventListener("click", () => $("#packageCompletionDialog").close()); $("#resetPackageCompletion").addEventListener("click", resetPackageCompletion);
$("#closePreviewDialog").addEventListener("click", () => $("#previewDialog").close()); $("#closePreviewDialogBottom").addEventListener("click", () => $("#previewDialog").close());
$("#editMapping").addEventListener("click", () => openMapping(jobs().find(job => job.id === $("#reviewJobId").value))); $("#captureMappingPage").addEventListener("click", captureMappingPage); $("#mappingJson").addEventListener("input", renderMappingChecklist); $("#mappingForm").addEventListener("submit", saveMapping); $("#closeMappingDialog").addEventListener("click", () => $("#mappingDialog").close()); $("#cancelMapping").addEventListener("click", () => $("#mappingDialog").close());
$("#riskForm").addEventListener("submit", saveRisk); $("#closeRiskDialog").addEventListener("click", () => $("#riskDialog").close()); $("#cancelRisk").addEventListener("click", () => $("#riskDialog").close());
$("#recoveryForm").addEventListener("submit", saveRecovery); $("#closeRecoveryDialog").addEventListener("click", () => $("#recoveryDialog").close()); $("#cancelRecovery").addEventListener("click", () => $("#recoveryDialog").close());
$("#finalReviewForm").addEventListener("submit", saveFinalReview); $("#closeFinalReviewDialog").addEventListener("click", () => $("#finalReviewDialog").close()); $("#cancelFinalReview").addEventListener("click", () => $("#finalReviewDialog").close());
$("#isolateForm").addEventListener("submit", saveIsolation); $("#closeIsolateDialog").addEventListener("click", () => $("#isolateDialog").close()); $("#cancelIsolation").addEventListener("click", () => $("#isolateDialog").close());
$("#closeTaskDialog").addEventListener("click", () => $("#taskDialog").close()); $("#closeTaskDialogBottom").addEventListener("click", () => $("#taskDialog").close());
$("#exportPreflight").addEventListener("click", exportPreflightReport);
setInterval(() => { if (!document.hidden) refresh({ quiet: true }); }, 15000);
$("#workflowStart").addEventListener("click", () => { document.querySelector(".queue-panel").scrollIntoView({ behavior: "smooth", block: "start" }); toast("请先导入商品包，勾选基础资料匹配的链接，再核验真实上架信息。"); });
$("#pickBatch").addEventListener("click", () => { document.querySelector(".queue-panel").scrollIntoView({ behavior: "smooth", block: "start" }); toast("在队列中勾选本批链接；建议每批不超过 10 条。"); });
$("#workflowGuide").addEventListener("click", () => { toast("流程：核验店铺与类目 → 导入商品包 → 补齐真实价格/履约/退改 → 草稿填充 → 你在后台确认发布。"); });
document.querySelectorAll("[data-scroll]").forEach(button => button.addEventListener("click", () => { const target = document.querySelector(button.dataset.scroll); if (!target) return; const section=target.closest('details'); if(section)section.open=true; document.querySelectorAll(".nav-item").forEach(item => item.classList.toggle("active", item === button)); target.scrollIntoView({ behavior: "smooth", block: "start" }); }));
