import {variantSummary,previewImage} from './publishing-rules-ui.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={PAUSING:'正在暂停',CHECK_REQUIRED:'待检查',VERIFY_REQUIRED:'待核验',DATA_INVALID:'需补充',PENDING:'待上架',RUNNING:'运行中',WAITING_HUMAN:'等待人工',SUCCEEDED:'成功',FAILED:'失败',RETRY:'待重试',SKIPPED:'已跳过',READY:'待开始',PAUSED:'已暂停',COMPLETED:'已完成',PAUSED_CAPTCHA:'等待人工验证',RESULT_UNKNOWN:'结果待核验',DRY_RUN_COMPLETE:'已填好，未提交',VERIFIED:'成功'};
const pages={home:['首页仪表盘','检查店铺状态，继续今天的上架工作。'],tasks:['任务中心','导入资料、核对清单，并管理每个批次。'],monitor:['实时执行监控','查看当前步骤、执行进度与页面截图。'],exceptions:['异常中心','处理验证、失败和中断，从原任务继续。'],records:['上架记录','所有已核验成功的商品，默认禁止重复上架。'],settings:['系统设置','管理本机资料来源和执行开关。']};
let exiting=false,lastReceived=Date.now();
const entryParams=new URLSearchParams(location.search);
let entryApplied=false;
let state,route='',busy=false,offline=true,stream,selectedBatch=entryParams.get('batch')||'',preview,uploadId,recordPage=0,taskPage=0,confirmFn;
const date=v=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—',duration=ms=>`${Math.floor((ms||0)/60000)}分${Math.floor((ms||0)/1000)%60}秒`;
const badge=s=>`<span class="pill ${['SUCCEEDED','VERIFIED','COMPLETED'].includes(s)?'success':['FAILED'].includes(s)?'error':['WAITING_HUMAN','PAUSED_CAPTCHA','PAUSED','PAUSING','RESULT_UNKNOWN','RETRY','DATA_INVALID'].includes(s)?'warning':s==='RUNNING'?'running':''}">${esc(labels[s]||s)}</span>`;
const empty=(title,detail='')=>`<div class="empty"><strong>${esc(title)}</strong><small>${esc(detail)}</small></div>`;
function html(id,value){const el=$(id);if(el&&el.innerHTML!==value)el.innerHTML=value;}
function toast(message,error=false){$('toast').textContent=message;$('toast').className='toast'+(error?' error':'');$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,6500);}
async function api(path,input){const r=await fetch('/api/v1/'+path,input===undefined?{}:{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(['start','continue','retry','resume-single'].includes(path)?{...input,requestId:input.requestId||crypto.randomUUID()}:input)});const d=await r.json();if(!r.ok)throw Error(d.error||'操作失败');return d;}
async function action(fn){if(busy)return;busy=true;render();try{await fn();if(!exiting)await refresh();}catch(e){toast(e.message,true);if($('importDialog').open){$('importFeedback').textContent=e.message;$('importFeedback').classList.add('error');}}finally{busy=false;render();}}
async function refresh(){state=await api('state'+(selectedBatch?'?batch='+encodeURIComponent(selectedBatch):''));lastReceived=Date.now();offline=false;$('connection').hidden=true;navigate(false);render();}
function subscribe(){stream?.close();stream=new EventSource('/api/v1/events'+(selectedBatch?'?batch='+encodeURIComponent(selectedBatch):''));stream.addEventListener('state',event=>{state=JSON.parse(event.data);lastReceived=Date.now();offline=false;$('connection').hidden=true;navigate(false);render();});const lost=()=>{offline=true;$('connection').hidden=false;render();};stream.onerror=lost;stream.addEventListener('problem',lost);}
function stats(items){return items.map(([name,value,hint])=>`<div class="stat"><span>${esc(name)}</span><strong>${esc(value)}</strong><small>${esc(hint)}</small></div>`).join('');}
function notice(){if(state.execution?.state==='PAUSING')return '<div class="notice" role="alert"><p><strong>正在暂停，等待断点保存</strong><small>当前步骤尚未结束，不能确认安全暂停。请保留执行 Chrome。</small></p><a href="#monitor">查看当前步骤</a></div>';if(state.execution?.state==='VERIFY_REQUIRED')return '<div class="notice" role="alert"><p><strong>提交结果待核验</strong><small>不能按失败直接重新上架，请先核验原商品。</small></p><a href="#exceptions">查看核验条件</a></div>';if(state.exceptions.some(x=>x.captcha))return '<div class="notice" role="alert"><p><strong>任务已暂停，等待人工验证码</strong><small>请在专用 Chrome 完成验证，保留原页面，再到异常中心继续。</small></p><a class="button secondary small" href="#exceptions">处理验证码</a></div>';return !state.settings.executionEnabled?'<div class="notice"><p><strong>新任务执行已关闭</strong><small>可以导入、预览和查看记录。需要执行时，在系统设置中开启。</small></p><a class="button secondary small" href="#settings">查看设置</a></div>':!state.browser.loggedIn?'<div class="notice"><p><strong>先检查店铺登录状态</strong><small>在专用 Chrome 完成人工登录或验证后继续。</small></p><button class="small secondary" data-action="browser">打开店铺</button></div>':'';}
const controls=()=>'<div class="actions"><button id="startButton" data-action="start" class="primary">开始上架</button><button id="pauseButton" data-action="pause" class="secondary">暂停</button><button id="continueButton" data-action="continue" class="primary">继续执行</button><button id="retryButton" data-action="retry" class="secondary">重试失败任务</button></div>';
const picker=()=>'<label>查看批次 <select id="batchPicker" aria-label="查看批次"></select></label>';
function navigate(force=true){const next=location.hash.slice(1);const target=pages[next]?next:'home';if(!state)return;if(!force&&route===target)return;route=target;recordPage=taskPage=0;
 document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===route);a.setAttribute('aria-current',a.dataset.nav===route?'page':'false');});$('pageTitle').textContent=$('crumb').textContent=pages[route][0];$('pageDescription').textContent=pages[route][1];html('pageActions',route==='home'||route==='tasks'?'<button data-action="import" class="primary">＋ 导入商品资料</button>':route==='records'?'<a class="button secondary" href="/api/v1/records.csv" download>导出记录</a>':'');
 const home='<div id="notice"></div><section id="nextStep" class="next-step"></section><section id="homeStats" class="stats compact-stats" aria-label="任务概况"></section><section class="panel"><div class="panel-head"><h2>批次核对单</h2><a href="#tasks">查看任务 →</a></div><div id="homeBatch"></div></section><section class="panel"><div class="panel-head"><h2>需要我处理的商品</h2><a href="#exceptions">全部异常 →</a></div><div id="homeExceptions" class="table-wrap"></div></section><section class="panel"><div class="panel-head"><h2>最近核验记录</h2><a href="#records">全部记录 →</a></div><div id="homeRecords" class="table-wrap compact"></div></section>';

 const tasks='<div id="notice"></div><section class="panel"><div class="toolbar"><div class="filters">'+picker()+'</div>'+controls()+'</div><div id="batchSummary"></div><div class="toolbar"><div class="filters"><input id="taskSearch" type="search" aria-label="搜索任务" placeholder="搜索目的地或标题"><select id="taskFilter" aria-label="任务状态"><option value="">全部状态</option>'+Object.entries(labels).slice(0,7).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')+'</select></div><span id="taskCount" class="muted"></span></div><div id="taskTable" class="table-wrap"></div><div class="pagination"><button class="secondary small" data-action="task-prev" id="taskPrev">上一页</button><span id="taskPager"></span><button class="secondary small" data-action="task-next" id="taskNext">下一页</button></div></section>';
 const monitor='<div id="notice"></div><section class="panel"><div class="toolbar">'+picker()+controls()+'</div><div id="monitorCurrent"></div></section><section id="monitorStats" class="stats"></section><div class="split"><section class="panel"><div class="panel-head"><h2>最新页面截图</h2><span class="muted">来自当前任务</span></div><div id="monitorImage"></div></section><section class="panel"><div class="panel-head"><h2>步骤进展与证据</h2><span class="pill success" id="streamStatus">实时连接</span></div><ol id="monitorEvents" class="event-list"></ol></section></div>';
 const exceptions='<div id="notice"></div><section class="panel"><div class="toolbar"><label>异常类型 <select id="exceptionFilter" aria-label="异常类型"><option value="">全部类型</option>'+['验证码','待核验','资料问题','登录 / 浏览器','页面校验','执行中断','执行失败','待人工确认','仅填写完成'].map(x=>`<option>${x}</option>`).join('')+'</select></label><span id="exceptionSummary" class="muted"></span></div><div id="exceptionList" class="table-wrap"></div></section><section class="panel"><h2>处理说明</h2><dl class="kv"><dt>验证码 / 滑块</dt><dd>在专用 Chrome 人工完成，保留原页面，再点击继续。</dd><dt>提交结果不明</dt><dd>仅核验原商品结果，不重新提交。</dd><dt>步骤失败</dt><dd>先查看截图与日志，再选择有限重试；每条最多 3 次。</dd></dl></section>';
 const records='<section class="panel"><div class="toolbar"><div class="filters"><input id="recordSearch" type="search" aria-label="搜索上架记录" placeholder="搜索目的地、标题或商品 ID"></div><span id="recordCount" class="muted"></span></div><div class="notice success"><p>已核验成功的商品会自动排除，不会再次进入新任务。</p></div><div id="recordTable" class="table-wrap"></div><div class="pagination"><button class="secondary small" data-action="record-prev" id="recordPrev">上一页</button><span id="recordPager"></span><button class="secondary small" data-action="record-next" id="recordNext">下一页</button></div></section>';
 const settings='<div class="settings-section"><section class="panel"><div class="panel-head"><h2>店铺与浏览器</h2><button class="secondary" data-action="browser">打开专用 Chrome</button></div><div id="settingsBrowser"></div></section><section class="panel"><div class="panel-head"><div><h2>执行开关</h2><p>开启后仍需预览、生成任务，并手动点击开始。</p></div><span id="executionLabel" class="pill"></span></div><label class="check"><input type="checkbox" id="allowExecution">允许执行新任务及恢复任务</label><button class="secondary" data-action="save-execution">保存执行设置</button></section><section class="panel"><div class="panel-head"><h2>资料与配置检查</h2><button class="secondary" data-action="check">检查配置与登录</button></div><div id="configChecks"></div><div class="field"><label for="settingPool">商品资料 Excel</label><input id="settingPool"></div><div class="field"><label for="settingAssets">图片目录</label><input id="settingAssets"></div><details><summary>高级：热度来源与批次限制</summary><div class="field"><label for="settingHeat">热度 Excel</label><input id="settingHeat"></div><div class="form-grid"><div class="field"><label for="settingSheet">热度工作表</label><input id="settingSheet" readonly></div><div class="field"><label for="settingLimit">默认批次数量（1—20）</label><input id="settingLimit" type="number" min="1" max="20"></div></div></details><button class="primary" data-action="save-paths">保存资料设置</button></section><section class="panel"><h2>本机系统</h2><details><summary>高级：执行连接与内核校验</summary><div id="kernelInfo"></div></details><p class="muted">日常使用：双击“启动上架工作台”，等待浏览器打开。资料和状态仅保存在本机。</p><div class="actions" style="margin-top:16px"><a href="legacy.html" class="button secondary small">历史工具</a><button class="secondary danger small" data-action="shutdown">暂停并退出程序</button></div></section></div>';
 html('page',{home,tasks,monitor,exceptions,records,settings}[route]);
 if(route==='settings'){for(const [id,key]of [['settingPool','pool'],['settingAssets','assets'],['settingHeat','heat'],['settingSheet','sheet'],['settingLimit','limit']])$(id).value=state.settings[key];$('allowExecution').checked=state.settings.executionEnabled;}
 for(const id of ['taskSearch','taskFilter','recordSearch','exceptionFilter'])if($(id))$(id).oninput=()=>{taskPage=recordPage=0;render();};
 if($('batchPicker'))$('batchPicker').onchange=async()=>{selectedBatch=$('batchPicker').value;await action(refresh);subscribe();};render();
}
function recordTable(rows,compact=false){return rows.length?`<table><thead><tr><th>商品</th><th>商品 ID</th><th>状态</th>${compact?'':'<th>记录时间 / 来源</th><th>详情</th>'}</tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.destination)}</strong><small class="title-line">${esc(r.title)}</small></td><td class="nowrap">${r.url?`<a href="${esc(r.url)}" target="_blank" rel="noopener">${esc(r.itemId)} ↗</a>`:esc(r.itemId)}</td><td><span class="pill ${r.verified===false?'warning':'success'}">${esc(r.status||'已核验')}</span><small>禁止重复上架</small></td>${compact?'':`<td class="nowrap">${esc(date(r.at))}<small>${esc(r.timeBasis||'核验记录')} · ${esc(r.batchId?.slice(0,8)||'历史单条')}</small></td><td>${r.runId?`<button class="secondary small" data-detail="${esc(r.runId)}">查看记录</button>`:'<span class="muted">历史记录</span>'}</td>`}</tr>`).join('')}</tbody></table>`:empty('暂无上架记录','成功核验后的商品会显示在这里。');}
function eventList(events){return events.length?events.slice().reverse().map(e=>`<li><div class="event-top"><strong>${esc(e.label)}</strong><time>${esc(date(e.at))}</time></div><p>${e.kind==='STEP_VERIFIED'?'步骤已通过 · ':''}${e.durationMs!==undefined?(e.durationMs/1000).toFixed(1)+' 秒':''}</p>${e.screenshotError?`<p>本次截图未保存：${esc(e.screenshotError)}</p>`:''}${e.screenshot?`<a href="${esc(e.screenshot)}" target="_blank" rel="noopener">查看步骤截图 ↗</a>`:''}<details><summary>技术记录</summary><pre>${esc(e.technical?.kind||e.kind)}${e.technical?.step?' / '+esc(e.technical.step):''}
${esc(e.raw||e.reason||'无错误')}</pre></details></li>`).join(''):'<li class="empty">任务开始后显示每一步的状态与耗时。</li>';}
function checksView(checks){return '<ul class="check-list">'+checks.map(x=>`<li><span class="pill ${x.ok===true?'success':x.ok===false?'warning':''}">${x.ok===true?'通过':x.ok===false?'未通过':'待检查'}</span><div><strong>${esc(x.name)}</strong><small>${esc(x.detail)}</small></div></li>`).join('')+'</ul>';}
function nextStep(){const b=state.batch,issue=state.exceptions.find(x=>!x.dataOnly);let title,text,action;
 if(state.execution?.state==='PAUSING'){title='正在保存本次执行断点';text=state.execution.detail;action='<a class="button secondary" href="#monitor">查看暂停进度</a>';}
 else if(issue){title=issue.destination+' · '+(issue.category||'需要处理');text=issue.next||issue.reason;action='<a class="button primary" href="#exceptions">检查异常与恢复条件</a>';}
 else if(!state.browser.loggedIn){title='先检查执行浏览器';text='你正在访问工作台。上架由另一扇项目专用 Chrome 执行，登录状态必须单独确认。';action='<button class="primary" data-action="check">检查执行状态</button><button class="secondary" data-action="browser">打开执行 Chrome</button>';}
 else if(state.active){title=(state.currentTask?.city||state.currentTask?.country||'当前批次')+' · 执行中';text='串行处理当前批次；可以查看每一步的校验与截图。';action='<a class="button primary" href="#monitor">查看当前执行</a>';}
 else if(b&&['PAUSED','WAITING_HUMAN'].includes(b.state)){title='原批次等待恢复';text='继续前先核对恢复条件，保留原任务和页面。';action='<button class="primary" data-action="check-recovery">检查恢复条件</button><a class="button secondary" href="#tasks">继续任务入口</a>';}
 else{title=b?.state==='COMPLETED'?'本批已结束，结果可以逐条追溯':'从商品资料开始';text=b?.state==='COMPLETED'?`本批 ${b.total} 条，成功 ${b.counts.SUCCEEDED||0} 条；没有自动开启下一批。`:'只读识别 Excel 和图片，核对范围后再生成任务。';action='<button class="primary" data-action="import">导入并核对资料</button><a class="button secondary" href="#records">查看上架记录</a>';}
 return `<div><p class="eyebrow">下一步操作</p><h2>${esc(title)}</h2><p>${esc(text)}</p></div><div class="actions">${action}</div>`;
}
function exceptionTable(rows){return rows.length?`<table class="exceptions-table"><thead><tr><th>受影响商品</th><th>类型 / 原因</th><th>下一步与恢复条件</th><th>处理入口</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.destination)}</strong>${badge(x.state)}</td><td><strong>${esc(x.category||'待人工确认')}</strong>${x.dataOnly?`<p class="issue-summary">${esc(x.reason)}</p>`:''}<details><summary>查看原始说明</summary><pre>${esc(x.raw||x.reason||'未提供具体原因')}</pre></details></td><td>${esc(x.next||x.reason)}<small>${esc(x.condition||'重新检查原任务状态')}</small></td><td><div class="cell-actions">${x.dataOnly?'<button class="secondary small" data-action="import">重新导入校验</button>':`<button class="secondary small" data-detail="${x.id}">日志与截图</button><button class="secondary small" data-recovery-check="${x.id}">检查恢复条件</button>${x.captcha||x.category==='登录 / 浏览器'?'<button class="secondary small" data-action="browser">打开执行 Chrome</button>':''}<button class="primary small" data-recover="${x.id}" ${busy||offline||!state.settings.executionEnabled||state.active||x.exhausted?'disabled':''}>${x.exhausted?'重试次数已用完':x.state==='DRY_RUN_COMPLETE'?'查看填写结果':x.unknown?'仅核验原商品':x.retryable?'重试本批失败':'已处理，检查并继续'}</button>`}</div></td></tr>`).join('')}</tbody></table>`:empty('暂无待处理异常','已恢复成功的任务不会继续显示为异常。');}
function render(){if(!state)return;const b=state.batch,c=b?.counts||{},browser=state.browser;
 $('browserStatus').textContent='执行 Chrome · '+(offline?'待检查':browser.label||'待检查');$('browserStatus').className='pill '+(!offline&&browser.loggedIn?'success':'warning');
 html('sessionStrip',`<div><small>本地服务</small><strong>${offline?'连接中断':'正在运行'}</strong></div><div><small>执行浏览器 / 登录</small><strong>${esc(offline?'待检查':browser.label||'待检查')}</strong></div><div><small>执行状态</small><strong>${esc(offline?'待检查':state.execution?.label||'待检查')}</strong></div><button class="secondary small" data-action="check" ${busy||offline?'disabled':''}>重新检查</button><p class="strip-note">此页面只负责操作与监控；自动化在项目专用 Chrome 中执行。</p>`);$('exceptionCount').textContent=state.exceptions.length;$('exceptionCount').hidden=!state.exceptions.length;$('updated').textContent=offline?'连接已中断':'更新于 '+new Date(state.at).toLocaleTimeString('zh-CN',{hour12:false});
 $('testMode').hidden=state.testMode!==true;
 html('notice',notice());
 if($('batchPicker')){html('batchPicker',state.batches.map(x=>`<option value="${esc(x.id)}">${esc(date(x.at))} · ${esc(labels[x.state])} · ${x.id.slice(0,8)}</option>`).join('')||'<option value="">暂无批次</option>');$('batchPicker').value=b?.id||'';}
 const blocked=busy||offline||!state.settings.executionEnabled||!browser.loggedIn||!state.kernel.ok;
 if($('startButton')){$('startButton').disabled=blocked||!!state.active||b?.state!=='READY';$('pauseButton').disabled=busy||offline||!state.active||state.execution?.state==='PAUSING';$('pauseButton').textContent=state.execution?.state==='PAUSING'?'正在暂停…':'暂停';$('continueButton').disabled=blocked||!!state.active||!['PAUSED','WAITING_HUMAN'].includes(b?.state)||b?.items.some(x=>x.state==='WAITING_HUMAN'&&x.runState==='DRY_RUN_COMPLETE');$('retryButton').disabled=blocked||!!state.active||!b?.items.some(x=>x.state==='FAILED'&&x.attempts<x.maxAttempts);}
 if(route==='home'){
  html('homeStats',stats([['已上架商品',state.overview.published,'后台核验成功'],['累计批次',state.overview.totalBatches,'保留全部批次记录'],['需人工处理',state.overview.waiting,'资料、验证与执行异常'],['待重试失败',state.overview.failed,'按原任务有限重试']]));html('nextStep',nextStep());
  html('homeBatch',b?`<div class="panel-head"><strong>${esc(date(b.at))}</strong>${badge(b.state)}</div><p class="muted">${b.mode==='LIVE'?'正式上架':'仅填写'} · ${b.total} 个商品</p><div class="progress-label"><span>已成功 ${c.SUCCEEDED||0} / ${b.total}</span><span>失败 ${c.FAILED||0} · 等待人工 ${c.WAITING_HUMAN||0}</span></div><progress value="${c.SUCCEEDED||0}" max="${b.total}"></progress><small style="margin-top:14px">累计运行 ${duration(b.elapsedMs)} · 最大连续成功 ${b.max_consecutive}</small>`:empty('还没有任务批次','从导入商品资料开始。'));
  html('homeExceptions',exceptionTable(state.exceptions.slice(0,3)));html('homeRecords',recordTable(state.records.slice(0,5),true));
 }
 if(route==='tasks'){
  html('batchSummary',b?`<div class="panel-head"><p>本批 ${b.total} 条 · 成功 ${c.SUCCEEDED||0} · 失败 ${c.FAILED||0} · 等待人工 ${c.WAITING_HUMAN||0}</p>${badge(state.execution?.state==='PAUSING'&&state.active===b.id?'PAUSING':b.state)}</div><div class="scope-line">范围：${esc(b.confirmation?.scope||'本批全部商品')} · ${b.total} 条 · ${b.mode==='LIVE'?'正式上架':'仅检查首条'}<small>确认时间 ${esc(date(b.confirmation?.at||b.at))} · 批次 ${esc(b.id)}</small></div>`:'');
  const q=$('taskSearch').value.trim(),filter=$('taskFilter').value,all=(b?.items||[]).filter(x=>(!filter||x.state===filter)&&(!q||(x.destination+x.title+x.id).includes(q)));const pages=Math.max(1,Math.ceil(all.length/20));taskPage=Math.min(taskPage,pages-1);$('taskCount').textContent=`${all.length} 条任务`;
  html('taskTable',all.length?`<table><thead><tr><th>顺序</th><th>商品</th><th>资料 / 执行状态</th><th>执行次数</th><th>当前步骤 / 结果</th><th>详情</th></tr></thead><tbody>${all.slice(taskPage*20,taskPage*20+20).map(x=>`<tr><td>${x.position}<small>热度 ${x.rank}</small></td><td><strong>${esc(x.destination)}</strong><small class="title-line">${esc(x.title)}</small></td><td>${badge(x.displayState||x.state)}<small>${esc(x.completeness||'查看任务快照')}</small></td><td>${x.attempts} / ${x.maxAttempts}</td><td>${x.result?esc(x.result.itemId):esc(x.reason||x.step)}<small>${esc(x.result?.status||'')}</small></td><td>${x.runId?`<button class="secondary small" data-detail="${x.runId}">日志与截图</button>`:`<button class="secondary small" data-queue-detail="${x.id}">查看任务资料</button>`}</td></tr>`).join('')}</tbody></table>`:empty(q||filter?'没有匹配的任务':'尚未生成任务','导入资料并核对清单后，在这里开始。'));$('taskPager').textContent=`${taskPage+1} / ${pages}`;$('taskPrev').disabled=taskPage===0;$('taskNext').disabled=taskPage+1===pages;
 }
 if(route==='monitor'){
  const cur=b?.items.find(x=>x.id===b.current),last=b?.items.findLast(x=>x.result),shot=cur?.screenshot||last?.result?.screenshot;
  html('monitorCurrent',b?`<div class="monitor-current"><div><p class="large-status">${cur?'当前任务 · '+cur.position+' / '+b.total:'当前批次'}</p><h2>${esc(cur?.destination||(b.state==='COMPLETED'?'本批执行结束':'等待开始执行'))}</h2><p class="muted">${esc(cur?.reason||cur?.step||(b.state==='COMPLETED'?'所有任务已结束，系统不会自动扩展数量。':'核对资料和执行方式后，再开始本批任务。'))}</p></div>${badge(state.execution?.state==='PAUSING'&&state.active===b.id?'PAUSING':b.state)}</div><p class="scope-line">${esc(state.execution?.detail||'等待服务状态核验')}</p>`:empty('暂无执行任务','先在任务中心生成一个批次。'));
  html('monitorStats',stats([['本批总数',b?.total||0,'固定批次范围'],['成功 / 失败',`${c.SUCCEEDED||0} / ${c.FAILED||0}`,'后台核验结果'],['等待人工',c.WAITING_HUMAN||0,'需在执行浏览器中处理'],['运行耗时',duration(b?.elapsedMs),'按运行状态累计'],['当前连续成功',b?.consecutive||0,'最大连续 '+(b?.max_consecutive||0)]]));
  const latestEvidence=cur||state.events.findLast(e=>e.screenshot||e.screenshotError),actualShot=latestEvidence?.screenshotError?null:latestEvidence?.screenshot;
  html('monitorImage',actualShot?`<a class="screenshot-link" href="${esc(actualShot)}" target="_blank" rel="noopener"><img src="${esc(actualShot)}" alt="最近任务页面截图"></a>`:latestEvidence?.screenshotError?empty('本次截图未保存',latestEvidence.screenshotError):empty('暂无页面截图','截图保存成功后显示在这里。'));html('monitorEvents',eventList(state.events));$('streamStatus').textContent=offline?'连接中断':'实时连接';
 }
 if(route==='exceptions'){const rows=state.exceptions.filter(x=>!$('exceptionFilter').value||x.category===$('exceptionFilter').value);$('exceptionSummary').textContent=rows.length+' 项需要处理';html('exceptionList',exceptionTable(rows));}
 if(route==='records'){const q=$('recordSearch').value.trim(),all=state.records.filter(x=>!q||(x.destination+x.title+x.itemId).includes(q)),pages=Math.max(1,Math.ceil(all.length/15));recordPage=Math.min(recordPage,pages-1);html('recordTable',recordTable(all.slice(recordPage*15,recordPage*15+15)));$('recordCount').textContent=`${all.length} 条记录 · ${all.filter(x=>x.verified===false).length} 条待核验`;$('recordPager').textContent=`${recordPage+1} / ${pages}`;$('recordPrev').disabled=recordPage===0;$('recordNext').disabled=recordPage+1===pages;}
 if(route==='settings'){html('configChecks',state.configuration?`<p class="muted">检查时间 ${esc(date(state.configuration.at))}</p>`+checksView(state.configuration.checks):empty('配置待检查','检查文件路径、执行浏览器与店铺登录。文件存在不等于资料完整。'));html('settingsBrowser',`<dl class="kv"><dt>当前店铺</dt><dd>${esc(state.shop.name)}</dd><dt>浏览器</dt><dd>${browser.running===null?'待检查':browser.running?'项目专用 Chrome 正在运行':'未运行'}</dd><dt>登录状态</dt><dd>${esc(browser.label||'待检查')}<small>${esc(browser.reason)}</small></dd><dt>会话保存</dt><dd>由本机专用 Chrome 保存，后续任务复用。</dd></dl>`);$('executionLabel').textContent=state.settings.executionEnabled?'允许执行':'执行已暂停';$('executionLabel').className='pill '+(state.settings.executionEnabled?'success':'warning');html('kernelInfo',`<dl class="kv"><dt>上架内核</dt><dd>${state.kernel.ok?'冻结校验通过 · '+state.kernel.files+' 个文件':'文件发生变化，已阻止执行'}</dd><dt>执行连接</dt><dd>127.0.0.1:${state.configuration?.connection?.port||9222} · 仅项目专用浏览器</dd><dt>版本</dt><dd>工作台 V1 · 内核 ${esc(state.kernel.baseline.slice(0,7))}</dd><dt>批次上限</dt><dd>20 条，不自动续批</dd></dl>`);}
 $('recognize').disabled=busy||offline||!!state.active;$('createBatch').disabled=busy||offline||!preview?.tasks.length||!$('reviewed')?.checked;
}
function confirm(title,text,fn,human=false){$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('humanLabel').hidden=!human;$('humanChecked').checked=false;$('confirmAction').disabled=human;confirmFn=fn;$('confirmChecks').innerHTML='';$('confirmDialog').showModal();}
$('humanChecked').onchange=()=>{$('confirmAction').disabled=!$('humanChecked').checked;};$('confirmAction').onclick=()=>{$('confirmDialog').close();action(()=>confirmFn());};
function openImport(){if(!state)return;preview=null;uploadId=null;$('importInputs').hidden=false;$('importPreview').hidden=true;$('importPreview').innerHTML='';$('recognize').hidden=false;$('createBatch').hidden=true;for(const [id,key]of [['importPool','pool'],['importAssets','assets'],['importHeat','heat'],['importSheet','sheet'],['importLimit','limit']])$(id).value=state.settings[key];$('importFeedback').textContent='选择资料后，识别字段与图片。';$('importFeedback').classList.remove('error');$('importStep1').classList.add('active');$('importStep2').classList.remove('active');$('importDialog').showModal();}
async function recognize(){const limit=Number($('importLimit').value);if(!Number.isInteger(limit)||limit<1||limit>20)throw Error('本批数量必须为 1—20');$('importFeedback').textContent='正在只读识别并校验图片，请稍候…';const imported=await api('import',{pool:$('importPool').value,assets:$('importAssets').value,heat:$('importHeat').value,sheet:$('importSheet').value});preview=await api('publishing-preview',{importId:imported.importId,limit});$('importInputs').hidden=true;$('importPreview').hidden=false;$('recognize').hidden=true;$('createBatch').hidden=false;$('importStep1').classList.remove('active');$('importStep2').classList.add('active');$('importFeedback').textContent=`本批 ${preview.tasks.length} 条；排除 ${preview.excluded.length} 条重复或资料问题。请核对标题、价格、库存和全部素材。`;html('importPreview',`<div class="scope-line">${esc(preview.scope||'本批仅选择下方所列商品')}<small>${Object.entries(preview.classification||{}).map(([k,v])=>esc(k)+' '+v+' 条').join(' · ')}</small></div><div class="preview-grid">${preview.tasks.map((t,i)=>`<article><img src="/api/source/asset?batch=${preview.importId}&order=${t.priority}&group=main&index=0" alt="${esc(t.listing.city)}主图"><strong>${i+1}. ${esc(t.listing.city)}</strong><p>${esc(t.listing.title)}</p><p>¥${esc(t.business.price_cny)} · ${esc(t.business.inventory)} 件</p>${variantSummary(t)}<button class="secondary small" data-material="${i}">查看完整素材</button></article>`).join('')}</div><details><summary>排除原因（${preview.excluded.length} 条）</summary>${preview.excluded.map(x=>`<p><span class="pill">${esc(x.category||'需检查')}</span> ${esc(x.destination)}：${esc(x.reason)}</p>`).join('')}</details><label class="check"><input id="reviewed" type="checkbox">已核对本批标题、价格、库存及素材</label><div class="field short"><label for="executeMode">执行方式</label><select id="executeMode"><option value="DRY_RUN">仅检查首条，提交前暂停</option><option value="LIVE">正式上架本批商品</option></select></div>`);$('reviewed').onchange=render;}
async function details(id,queued=false){const d=await api((queued?'queue-task':'task')+'?id='+encodeURIComponent(id));$('detailTitle').textContent=d.task.listing.city||d.task.listing.country;html('detailBody',`${badge(d.state)}${variantSummary(d.task)}<p style="margin-top:14px">${esc(d.task.listing.title)}</p><dl class="kv"><dt>任务编号</dt><dd>${esc(d.id)}</dd><dt>价格 / 库存</dt><dd>¥${esc(d.task.business.price_cny)} / ${esc(d.task.business.inventory)} 件</dd><dt>来源批次</dt><dd>${esc(d.batchId||'历史单条任务')}</dd><dt>导入编号</dt><dd>${esc(d.importId||'历史记录未提供')}</dd><dt>来源</dt><dd>${esc(d.task.source.sheet)} · 第 ${d.task.source.row||'未记录'} 行</dd><dt>断点步骤</dt><dd>${esc(d.checkpoint?.step||'无断点步骤')}</dd><dt>恢复条件</dt><dd>${esc(d.issue?.condition||'无需恢复')}</dd><dt>当前说明</dt><dd>${esc(d.reason||'状态已记录')}</dd>${d.result?`<dt>商品 ID</dt><dd>${esc(d.result.itemId)} · ${esc(d.result.status)}</dd>`:''}</dl><h3>步骤与截图</h3><ol class="event-list">${eventList(d.events)}</ol>`);$('detailDialog').showModal();}
async function showRecovery(input){const d=await api('recovery-check',input);$('detailTitle').textContent='恢复条件检查';html('detailBody',`<p>${d.ready?'检查通过；仍需明确点击继续，不自动执行。':'尚未具备恢复条件，任务不会继续。'}</p>`+checksView(d.checks));$('detailDialog').showModal();return d;}
async function requireRecovery(input){const d=await api('recovery-check',input);if(!d.ready){$('detailTitle').textContent='恢复条件未通过';html('detailBody',checksView(d.checks));$('detailDialog').showModal();throw Error('恢复条件未通过，请按检查结果处理。');}return d;}
async function upload(files,kind){const chosen=[...files].filter(f=>/\.(xlsx|png|jpe?g|webp)$/i.test(f.name));if(!chosen.length)throw Error('没有可上传的 Excel 或图片文件');if(!uploadId)uploadId=(await api('upload',{begin:true})).id;let result;$('uploadProgress').hidden=false;$('uploadProgress').max=chosen.length;try{for(let i=0;i<chosen.length;i++){const file=chosen[i];if(file.size>16*1024*1024)throw Error('单个文件不能超过 16MB：'+file.name);$('importFeedback').textContent=`正在上传 ${i+1}/${chosen.length}：${file.name}`;const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});result=await api('upload',{id:uploadId,name:kind+'/'+(file.webkitRelativePath||file.name),data});$('uploadProgress').value=i+1;}if(kind==='images')$('importAssets').value=result.root+'/images';else $(kind==='pool'?'importPool':'importHeat').value=result.path;$('importFeedback').textContent=`已上传 ${chosen.length} 个文件，点击“识别并预览”继续。`;}finally{$('uploadProgress').hidden=true;}}
for(const [id,kind] of [['poolFile','pool'],['heatFile','heat'],['imageFiles','images']])$(id).onchange=()=>action(()=>upload($(id).files,kind));
document.addEventListener('click',event=>{const button=event.target.closest('button,[data-open-import]');if(!button||button.disabled)return;if(button.dataset.close){if(busy&&button.dataset.close==='importDialog'){toast('当前操作仍在进行，请等待完成。');return;}$(button.dataset.close).close();return;}
 if(button.hasAttribute('data-open-import')){event.preventDefault();openImport();return;}
 if(button.dataset.queueDetail){action(()=>details(button.dataset.queueDetail,true));return;}
 if(button.dataset.recoveryCheck){const x=state.exceptions.find(x=>x.id===button.dataset.recoveryCheck);action(()=>showRecovery({id:x.batchId||x.id,single:!x.batchId}));return;}
 if(button.dataset.detail){action(()=>details(button.dataset.detail));return;}
 if(button.dataset.material!==undefined){const t=preview.tasks[Number(button.dataset.material)];$('detailTitle').textContent=t.listing.city+' · 全部素材';html('detailBody',`<p>${esc(t.listing.title)}</p><dl class="kv">${[['类目',t.business.category_path],['价格',t.business.price_cny],['库存',t.business.inventory],['发货',t.business.shipping_time],['发货地',t.business.ship_from]].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl><div class="preview-grid">${Object.entries(t.assets).flatMap(([group,assets])=>assets.map((a,i)=>`<article><img src="${previewImage(preview,t,group,i)}" alt="${group==='main'?'主图':group==='secondary'?'副图':'详情'} ${i+1}"><p>${esc(a.path.split(/[\\/]/).at(-1))}</p></article>`)).join('')}</div>`);$('detailDialog').showModal();return;}
 if(button.dataset.recover){const x=state.exceptions.find(x=>x.id===button.dataset.recover);if(x.state==='DRY_RUN_COMPLETE'){action(()=>details(x.id));return;}if(x.batchId&&state.batch?.id!==x.batchId){toast('请先在任务中心选择原批次，再核对恢复范围',true);return;}const confirmed=x.batchId?{id:x.batchId,scope:state.batch.executionScope}:null;confirm(x.unknown?'核验原商品结果':'继续原任务',x.retryable?'将有限重试原批次中所有可重试的失败任务。':x.reason,async()=>{await requireRecovery({id:x.batchId||x.id,single:!x.batchId,operation:x.retryable?'retry':'continue'});if(x.batchId)await api(x.retryable?'retry':'continue',{...confirmed,humanVerified:x.captcha});else await api('resume-single',{id:x.id,humanVerified:x.captcha});selectedBatch=x.batchId||'';location.hash='monitor';subscribe();},x.captcha);return;}
 const op=button.dataset.action;if(!op)return;
 if(op==='import'){openImport();return;}if(op==='recognize'){action(recognize);return;}
 if(op==='create'){action(async()=>{const batch=await api('create',{importId:preview.importId,draftId:preview.draftId,limit:preview.limit,mode:$('executeMode').value,review:{reviewed:$('reviewed').checked,selectionHash:preview.selectionHash,authorization:'操作者在本地工作台 V1 核对本批资料与执行方式',at:new Date().toISOString()}});selectedBatch=batch.id;$('importDialog').close();location.hash='tasks';subscribe();toast('任务已生成，尚未开始执行。');});return;}
 if(['start','continue','retry'].includes(op)){const confirmed={id:state.batch.id,scope:state.batch.executionScope};const human=state.exceptions.some(x=>x.batchId===state.batch.id&&x.captcha);confirm(op==='start'?'开始本批任务':op==='retry'?'重试失败任务':'继续原批次',`${state.shop.name} · 本批共 ${state.batch.total} 条 · ${state.batch.mode==='LIVE'?'正式上架':'仅填写，提交前停止'}。范围：${state.batch.items.filter(x=>op==='retry'?x.state==='FAILED'&&x.attempts<x.maxAttempts:!['SUCCEEDED','SKIPPED','FAILED'].includes(x.state)).map(x=>x.destination).join('、')||'无待执行项'}。已成功商品不会再次提交。`,async()=>{if(confirmed.id!==state.batch?.id||confirmed.scope!==state.batch?.executionScope)throw Error('批次范围或状态已变化，请重新核对');if(op!=='start')await requireRecovery({...confirmed,operation:op});await api(op,{...confirmed,humanVerified:human});location.hash='monitor';},human);return;}
 if(op==='pause'){action(async()=>{await api('pause',{});toast('已请求暂停，将保存当前断点。');});return;}
 if(op==='check'){action(async()=>{await api('check',{});toast('已更新配置与执行浏览器检查结果。');});return;}if(op==='check-recovery'){action(()=>showRecovery({id:state.batch.id}));return;}
 if(op==='browser'){action(()=>api('browser',{}));return;}if(op==='refresh'){action(async()=>{await refresh();subscribe();});return;}
 if(op==='save-execution'){const enabled=$('allowExecution').checked;const save=async()=>{await api('settings',{executionEnabled:enabled,confirmShop:state.shop.name});toast(enabled?'执行已允许，仍需从任务中心手动开始。':'新任务执行已关闭。');};if(enabled)confirm('允许执行任务',`目标店铺：${state.shop.name}。开启后可手动开始已核对的任务；不会自动上架。`,save);else action(save);return;}
 if(op==='save-paths'){action(async()=>{await api('settings',{pool:$('settingPool').value,assets:$('settingAssets').value,heat:$('settingHeat').value,sheet:$('settingSheet').value,limit:Number($('settingLimit').value)});toast('默认资料设置已保存。');});return;}
 if(op==='shutdown'){confirm('暂停并退出程序','当前任务将先保存断点。下次双击启动入口后可继续。',async()=>{const response=await fetch('/api/program/shutdown',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});if(!response.ok)throw Error((await response.json()).error||'退出请求未被接受，请重试');exiting=true;stream?.close();offline=true;$('connection').textContent='已请求退出；正在等待任务保存断点与服务关闭。再次打开时将重新检查真实状态。';$('connection').hidden=false;});return;}
 if(op.startsWith('record-')){recordPage+=op==='record-next'?1:-1;render();}if(op.startsWith('task-')){taskPage+=op==='task-next'?1:-1;render();}
});
$('importDialog').addEventListener('cancel',event=>{if(busy)event.preventDefault();});
setInterval(()=>{if(state&&!exiting&&!offline&&Date.now()-lastReceived>12000){offline=true;$('connection').hidden=false;render();}},3000);
window.addEventListener('hashchange',()=>navigate());
refresh().then(()=>{
 if(!entryApplied){entryApplied=true;const q=entryParams.get('destination')||'';if(route==='records'&&$('recordSearch'))$('recordSearch').value=q;if(route==='tasks'&&$('taskSearch'))$('taskSearch').value=q;render();if(entryParams.get('portal')==='import')openImport();}
 subscribe();
}).catch(e=>{offline=true;$('connection').hidden=false;html('page',empty('本地服务尚未就绪','双击“启动上架工作台”，等待服务启动后刷新。'));toast(e.message,true);subscribe();});
