const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clock=v=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'尚未检查';
export function createSetupUI({get,post,getData,isConnected,refresh,openRules,openPermission}){
 let host,state,step=1,pending='',error='',message='',loading=false,mode='host',format='standard',uploadFiles=[],legacyFiles={},report=null,loaded=false,rootDraft='',storageDraft='',legacyDraft={},connectHint='';
 const engine=()=>getData()?.engine;
 const api=(action,input)=>post('/api/v1/setup/'+action,input);
 const button=(label,action,primary=false,extra='')=>`<button type="button" data-setup="${action}" ${primary?'class="primary"':''} ${extra}>${label}</button>`;
 function drafts(){if(!host)return;for(const [id,key]of [['setupRoot','root'],['setupStorage','storage']]){const e=host.querySelector('#'+id);if(e){if(key==='root')rootDraft=e.value;else storageDraft=e.value;}}for(const key of ['heat','pool','assets','sheet']){const input=host.querySelector('#setupLegacy-'+key);if(input)legacyDraft[key]=input.value;}}
 async function load(){if(loading)return;loading=true;try{state=await get('/api/v1/setup/state');loaded=true;report=state.report;format=state.source?.format==='travel-os-template-v1'?'standard':state.source?'legacy':state.format==='standard'?'standard':'standard';storageDraft=state.storageRoot||'';rootDraft=state.source?.format==='travel-os-template-v1'?engine().settings.assets:'';legacyDraft={...engine().settings};if(state.report?.ready&&!state.report.stale)step=4;else if(state.source)step=3;}catch(e){error=e.message;}finally{loading=false;draw();}}
 function shell(content){return `<div class="page-heading"><div><h1>资料设置</h1><p>第一次设置清楚，之后只换资料、检查状态、确认执行。</p></div><a class="setup-guide-link" href="#settings" data-setup="guide">新电脑简易教程 ↗</a></div><div class="setup-shell"><nav class="setup-steps" aria-label="首次配置步骤">${['存放位置','导入资料','连接店铺','准备检查'].map((label,i)=>`<button type="button" data-setup="step" data-step="${i+1}" aria-current="${step===i+1?'step':'false'}"><span>${i+1}</span><b>${label}</b></button>`).join('')}</nav><section class="setup-content" aria-labelledby="setupStepTitle" aria-busy="${!!pending}"><div id="setupFeedback" class="setup-feedback" role="${error?'alert':'status'}" ${!error&&!message&&!pending?'hidden':''} data-error="${!!error}">${esc(pending||error||message)}</div>${content}</section></div>`;}
 function sourceForm(){const shared=`<div class="setup-choice" role="group" aria-label="资料位置">${button('资料已在工作台主机','host',false,`aria-pressed="${mode==='host'}"`)}${button('从当前电脑上传','upload',false,`aria-pressed="${mode==='upload'}"`)}</div><div class="setup-format"><label>资料格式<select id="setupFormat"><option value="standard" ${format==='standard'?'selected':''}>标准模板（新资料推荐）</option><option value="legacy" ${format==='legacy'?'selected':''}>原有 Excel（兼容已有资料）</option></select></label><a class="button" href="/api/v1/setup/template" download>下载固定模板 ↓</a></div>`;
 if(mode==='host')return shared+(format==='standard'?`<label>模板资料文件夹（工作台主机）<div class="setup-path"><input id="setupRoot" value="${esc(rootDraft)}" placeholder="选择包含商品资料.xlsx的文件夹" autocomplete="off">${button('浏览主机目录','browse-source')}</div></label>`:`<div class="setup-legacy">${[['heat','热度 Excel'],['pool','商品资料 Excel'],['assets','图片目录'],['sheet','热度工作表']].map(([key,name])=>`<label>${name}<input id="setupLegacy-${key}" value="${esc(legacyDraft[key]||'')}" autocomplete="off"></label>`).join('')}</div><p class="setup-note">原资料直接引用，无需复制或改名。路径属于运行工作台的电脑。</p>`);
 if(!state?.storageRoot)return shared+`<div class="setup-warning">尚未选择上传存放位置。${button('回到第1步选择位置','storage-step')}</div>`;
 return shared+`<div class="setup-destination"><small>上传后保存在工作台主机</small><strong>${esc(state.storageRoot)} / 导入批次</strong></div>`+(format==='standard'?`<label class="setup-upload">选择按模板整理好的整个文件夹<input id="setupFolder" type="file" webkitdirectory multiple><small>包含商品资料.xlsx及五组图片目录。每个文件不超过16MB。</small></label><p>${uploadFiles.length?`已选择 ${uploadFiles.length} 个 Excel / 图片文件`:'尚未选择资料'}</p>`:`<div class="setup-legacy">${[['heat','热度 Excel'],['pool','商品资料 Excel'],['images','图片文件夹']].map(([key,label])=>`<label>${label}<input type="file" id="setupUpload-${key}" ${key==='images'?'webkitdirectory multiple':'accept=".xlsx"'}><small>${esc(legacyFiles[key]?.length?`已选择 ${legacyFiles[key].length} 个文件`:'尚未选择')}</small></label>`).join('')}<label>热度工作表<input id="setupLegacy-sheet" value="${esc(legacyDraft.sheet||'境外城市热度')}"></label></div>`);
 }
 function draw(){if(!host)return;const e=engine();if(!e)return;if(!loaded){host.innerHTML=shell(`<h2 id="setupStepTitle">${error?'暂时无法读取配置':'正在读取首次配置…'}</h2>${error?button('重新读取','reload',true):''}`);bind();return;}
 let content='';
 if(step===1)content=`<div class="setup-heading"><span>01 / 存放位置</span><h2 id="setupStepTitle">先选好资料放在哪个盘</h2><p>上传的 Excel 与图片都保存在工作台主机。已有资料可以直接引用。</p></div><label>上传存放目录<div class="setup-path"><input id="setupStorage" value="${esc(storageDraft)}" placeholder="例如 D:\\TravelOS资料" autocomplete="off">${button('浏览主机目录','browse-storage')}</div></label><div class="setup-note">这是运行工作台的电脑（${esc(location.hostname)}），不是另一台正在访问网页的电脑。位置不可用时会报错，不自动改存 C 盘。</div><div class="setup-actions">${button('保存位置，下一步','save-storage',true)}${button('已有主机资料，直接导入','skip-storage')}</div>`;
 if(step===2)content=`<div class="setup-heading"><span>02 / 导入资料</span><h2 id="setupStepTitle">一套资料，一次识别</h2><p>标准模板与原有资料都可使用。导入后先看缺项，再创建任务。</p></div>${sourceForm()}<details class="setup-template-help"><summary>模板怎么整理</summary><p>一个店铺一个文件夹，商品资料.xlsx填写商品与店铺设置。主图按商品序号命名；副图A、B各4张，详情首页2张，详情正文7–12张。文件名和填写说明均在下载包内。</p><p>未启用随机规则时使用副图A与首页01。需要随机时，导入后核对发布随机规则。</p></details><div class="setup-actions">${button('识别并保存资料','import',true)}${button('上一步','back')}</div><div id="setupImportResult">${state.source?`<p class="setup-note">当前已识别 ${esc(state.source.summary?.total??0)} 条商品；资料待补充 ${esc(state.source.summary?.blocked??0)} 条。导入总量不等于每批最多20条的预览数量。</p>`:''}</div>`;
 if(step===3)content=`<div class="setup-heading"><span>03 / 连接店铺</span><h2 id="setupStepTitle">登录这次要执行的店铺</h2><p>点击连接，在工作台主机的专用 Chrome 中人工登录。系统会自动核对店铺身份。</p></div><div class="setup-shop"><span class="setup-shop-icon" aria-hidden="true">↗</span><div><small>当前执行店铺</small><h3>${esc(e.shop.name)}</h3><strong id="setupLoginState"></strong><p id="setupLoginReason"></p><small id="setupLoginTime"></small></div>${button('连接店铺','connect',true)}</div><p class="setup-note" id="setupConnectHint">${esc(connectHint||'在其他电脑普通浏览器中登录，不会改变本机执行 Chrome 的状态。')}</p><div class="setup-actions">${button('下一步，检查准备情况','next')}${button('上一步','back')}<a href="#shops">管理店铺</a></div>`;
 if(step===4){const stale=report?.stale,checks=report?.checks||[],fresh=report?.ready&&!stale&&e.browser.loggedIn&&isConnected();content=`<div class="setup-heading"><span>04 / 准备检查</span><h2 id="setupStepTitle">${fresh?'准备检查已通过':stale?'资料已变化，请重新检查':'看看还有哪一步需要处理'}</h2><p>核对文件、资料内容、店铺身份与运行环境。检查不会启动任务或开启执行许可。</p></div><div class="setup-actions">${button('检查准备情况','check',true)}${button('上一步','back')}${fresh?'<a class="button" href="#tasks">前往任务，核对本批商品 →</a>':''}</div>${report?`<p class="setup-note">最近检查：${clock(report.at)}${stale?' · 旧结果已失效':''}。文件或登录状态变化后请重新检查。</p><div class="setup-checks">${['资料位置','资料内容','店铺连接','运行环境'].map(group=>`<section><h3>${group}</h3>${checks.filter(c=>c.group===group).map(c=>`<div ${c.group==='店铺连接'?'data-report-login':''} class="setup-check ${c.ok?'good':'bad'}"><strong>${c.ok?'通过':'待处理'} · ${esc(c.name)}</strong><p>${esc(c.detail)}</p>${!c.ok?button('去处理','fix',false,`data-step="${c.step}"`):''}</div>`).join('')}</section>`).join('')}</div>`:'<div class="setup-empty">点击检查后，这里会逐项告诉你结果与处理方法。</div>'}${e.publishingRules?.checkpoint?`<p class="setup-warning" data-rules-paused role="alert">属性读取已暂停：${esc(e.publishingRules.checkpoint.reason)}。人工处理后打开下方配置重新读取。</p>`:""}<details class="setup-more"><summary>发布随机规则与执行许可</summary><p>${e.publishingRules?.enabled?'随机规则已启用，仍需核对是否对应本次资料。':'未启用随机规则。标准模板默认使用副图A及首页01。'}</p><div class="setup-actions">${button('配置图片与属性','rules',false,'id="publishingConfigure"')}${button('设置执行许可','permission')}</div><p>登录或准备检查通过不代表平台发布验收通过。开启许可后仍需核对商品并手动开始。</p></details>`;}
 host.innerHTML=shell(content);bind();paint();
 }
 function bind(){host.querySelectorAll('[data-setup]').forEach(b=>b.onclick=event=>{event.preventDefault();const action=b.dataset.setup;drafts();if(pending)return;if(action==='step'||action==='fix'){step=Number(b.dataset.step);error='';message='';draw();host.querySelector('#setupStepTitle')?.scrollIntoView({block:'nearest'});return;}actions(action);});host.querySelector('#setupFormat')?.addEventListener('change',event=>{drafts();format=event.target.value;error='';message='';draw();});host.querySelector('#setupFolder')?.addEventListener('change',event=>{uploadFiles=Array.from(event.target.files).filter(f=>/\.(xlsx|png|jpe?g|webp)$/i.test(f.name));drafts();draw();});for(const key of ['heat','pool','images'])host.querySelector('#setupUpload-'+key)?.addEventListener('change',event=>{legacyFiles[key]=Array.from(event.target.files).filter(f=>key==='images'?/\.(png|jpe?g|webp)$/i.test(f.name):/\.xlsx$/i.test(f.name));drafts();draw();});}
 function paint(){if(!host)return;const e=engine();if(step===4&&report?.ready){const title=host.querySelector('#setupStepTitle'),next=host.querySelector('a[href="#tasks"]');const changed=state?.source?.id!==e.latestImport;const unavailable=!isConnected()||!e.browser.loggedIn||changed||report.stale;if(title&&!pending&&unavailable)title.textContent=changed||report.stale?'资料已变化，请重新检查':'店铺连接已变化，请重新检查';if(next)next.hidden=unavailable;const login=host.querySelector('[data-report-login]');if(login&&(!isConnected()||!e.browser.loggedIn)){login.className='setup-check bad';login.querySelector('strong').textContent='需复查 · 店铺连接已变化';login.querySelector('p').textContent=!isConnected()?'服务连接中断，恢复后请重新检查':e.browser.reason||'请重新连接店铺并检查';}}host.querySelectorAll('button,input,select').forEach(b=>b.disabled=!!pending||!isConnected());const status=host.querySelector('#setupLoginState');if(status){status.textContent=e.browser.loginState==='WRONG_SHOP'?'店铺不匹配':e.browser.label||'待检查';status.className=e.browser.loggedIn?'setup-connected':'setup-unconnected';host.querySelector('#setupLoginReason').textContent=e.browser.reason||'等待检查目标店铺';host.querySelector('#setupLoginTime').textContent='检查时间：'+clock(e.browser.checkedAt);}}
 async function run(label,fn){pending=label;error='';message='';draw();try{await fn();}catch(e){error=e.message;}finally{pending='';draw();}}
 async function upload(files){if(!files.length)throw Error('请先选择完整资料');if(files.length>5000)throw Error('一次最多5000个文件，请分店铺整理');const names=new Set();for(const {file,name}of files){if(file.size>16*1024*1024||file.size===0)throw Error(`${name}：文件为空或超过16MB`);if(names.has(name.toLowerCase()))throw Error('资料中有重复文件：'+name);names.add(name.toLowerCase());}
 const session=await api('upload',{begin:true});for(let i=0;i<files.length;i++){const {file,name}=files[i];pending=`正在上传 ${i+1} / ${files.length}：${file.name}`;const feedback=host.querySelector('#setupFeedback');if(feedback)feedback.textContent=pending;const bytes=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('无法读取：'+file.name));reader.readAsDataURL(file);});await api('upload',{id:session.id,name,data:bytes});}return session.id;}
 const relativeFile=file=>(file.webkitRelativePath||file.name).split('/').slice(file.webkitRelativePath?1:0).join('/');
 async function actions(action){
  if(action==='reload'){error='';await load();return;}
  if(['host','upload'].includes(action)){mode=action;error='';message='';draw();return;}
  if(action==='next'){step=Math.min(4,step+1);error='';message='';draw();return;}
  if(action==='back'){step=Math.max(1,step-1);error='';message='';draw();return;}
  if(action==='skip-storage'){step=2;mode='host';draw();return;}
  if(action==='storage-step'){step=1;draw();return;}
  if(action==='browse-storage'||action==='browse-source'){await browse(action==='browse-storage'?'storage':'root');return;}
  if(action==='guide'){guide();return;}
  if(action==='rules'){await openRules();return;}
  if(action==='permission'){openPermission();return;}
  if(action==='save-storage')await run('正在确认存放位置…',async()=>{const result=await api('storage',{path:storageDraft.trim()});state=await get('/api/v1/setup/state');storageDraft=result.root;report=null;step=2;message='上传位置已保存：'+result.root;});
  if(action==='import')await run('正在识别资料…',async()=>{
   let input={format,root:rootDraft.trim(),...legacyDraft};
   if(mode==='upload'){
    if(!state.storageRoot)throw Error('请先到第1步选择上传存放位置');
    let files;if(format==='standard'){files=uploadFiles.map(file=>({file,name:relativeFile(file)}));if(!files.some(f=>f.name==='商品资料.xlsx'))throw Error('请选择直接包含商品资料.xlsx的模板文件夹');}
    else{if(!legacyFiles.heat?.length||!legacyFiles.pool?.length||!legacyFiles.images?.length)throw Error('请分别选择热度Excel、商品Excel和图片文件夹');files=[{file:legacyFiles.heat[0],name:'热度.xlsx'},{file:legacyFiles.pool[0],name:'商品.xlsx'},...legacyFiles.images.map(file=>({file,name:'图片/'+relativeFile(file)}))];}
    input.uploadId=await upload(files);pending='上传完成，正在识别并校验资料…';
   }
   const result=await api('import',input);await refresh();state=await get('/api/v1/setup/state');report=null;legacyDraft={...engine().settings};message=`已识别 ${result.summary.total} 条商品，${result.summary.blocked} 条待补充。资料已保存，不会自动创建或启动任务。`;if(result.issues.length){error=result.issues.slice(0,8).map(x=>`${x.destination}（第${x.row}行）：${x.issues.join('；')}`).join('\n');}else step=3;
  });
  if(action==='connect')await run('正在主机上连接执行 Chrome…',async()=>{await post('/api/v1/browser');connectHint='已在工作台主机打开执行 Chrome。请人工完成登录或验证码；本页自动更新状态。';await refresh();});
  if(action==='check')await run('正在检查文件、资料与店铺…',async()=>{report=await api('check');state=await get('/api/v1/setup/state');await refresh();message=report.ready?'准备检查通过，请到任务页面核对本批商品。':'有项目需要处理，原因已在下方展开。';});
 }
 async function browse(target){
  const dialog=document.createElement('dialog');dialog.className='setup-folder-dialog';document.body.append(dialog);
  const close=()=>{dialog.close();dialog.remove();};dialog.addEventListener('cancel',event=>{event.preventDefault();close();});
  async function show(path=''){try{const result=await get('/api/v1/setup/folders'+(path?'?path='+encodeURIComponent(path):''));dialog.innerHTML=`<div class="setup-picker-head"><h2>浏览工作台主机目录</h2><button type="button" aria-label="关闭目录选择">关闭</button></div><p>主机：${esc(location.hostname)}。选择目录不会读取浏览器登录资料。</p><p class="setup-picker-path">${esc(result.path||'选择磁盘')}</p><div class="setup-folder-list">${result.path?button('← 返回上一级','parent'):''}${result.items.map((x,i)=>`<button type="button" data-folder="${i}">▱ ${esc(x.name)}${x.freeBytes!==undefined?`<small>剩余 ${(x.freeBytes/1024**3).toFixed(1)} GB</small>`:''}</button>`).join('')}</div>${result.path?`<div class="setup-actions">${button(target==='storage'?(result.parent?'使用此存放目录':'在此磁盘创建 TravelOS资料'):'使用此资料文件夹','select',true)}</div>`:''}`;dialog.querySelector('[aria-label]')?.addEventListener('click',close);dialog.querySelector('[data-setup="parent"]')?.addEventListener('click',()=>show(result.parent));dialog.querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>show(result.items[Number(b.dataset.folder)].path));dialog.querySelector('[data-setup="select"]')?.addEventListener('click',()=>{if(target==='storage')storageDraft=result.parent?result.path:result.path.replace(/[\\/]$/,'')+'/TravelOS资料';else rootDraft=result.path;close();draw();});}catch(e){dialog.innerHTML=`<p role="alert">${esc(e.message)}</p><button type="button">关闭</button>`;dialog.querySelector('button').onclick=close;}}
  dialog.showModal();await show();
 }
 function guide(){const d=document.createElement('dialog');d.className='setup-folder-dialog';d.innerHTML=`<h2>新电脑 · 四步开始</h2><ol class="setup-guide"><li><strong>安装并启动</strong><p>打开项目目录，首次双击“安装工作台.cmd”，安装检查通过后双击“启动上架工作台.vbs”。进入资料设置，选择资料存放位置。</p></li><li><strong>导入资料</strong><p>下载固定模板，填写真实商品资料并放好图片。选择整套资料文件夹，点“识别并保存资料”，按提示补齐缺项。</p></li><li><strong>连接店铺</strong><p>点击“连接店铺”，在运行工作台的电脑上人工登录专用Chrome，等待页面显示已登录目标店铺。</p></li><li><strong>检查并核对任务</strong><p>点“检查准备情况”。通过后进入任务页，预览商品；需要执行时另行开启许可并手动开始。正式发布有独立确认。</p></li></ol><p>如果只是另一台电脑访问同一局域网工作台，不用重复安装；主机须保持开机，登录仍在主机完成。</p><div class="setup-actions"><button type="button" class="primary">知道了</button></div>`;document.body.append(d);const close=()=>{d.close();d.remove();};d.querySelector('button').onclick=close;d.addEventListener('cancel',event=>{event.preventDefault();close();});d.showModal();}
 return {mount(element){host=element;if(!loaded&&!loading)load();draw();},paint,reset(){loaded=false;},connect(){step=3;draw();}};
}
