import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {SourceStore,digest} from '../source-store.mjs';
import {BatchStore} from '../batch-store.mjs';
import {BatchWorkflow} from '../batch-workflow.mjs';
const shop={id:'wuzhou-changyou',name:'五洲畅游'};
const task=n=>({schemaVersion:2,taskId:'task-'+n,shopId:shop.id,priority:n,source:{},listing:{type:'city',country:'国家',city:'城市'+n,title:'标题'+n},assets:{main:[],secondary:[],details:[]},business:{},adapterIssues:[]});
const result=id=>({itemId:'100'+id.replace(/\D/g,''),status:'出售中',rowText:'verified',screenshot:'evidence.png'});
async function fixture(t,n=3){const dir=await mkdtemp(join(tmpdir(),'ly-batch-'));const source=new SourceStore(join(dir,'state.sqlite'));t.after(async()=>{source.close();await rm(dir,{recursive:true,force:true});});const tasks=Array.from({length:n},(_,i)=>task(i+1)),importId=source.imported({sheet:'境外城市热度',sourceHash:'heat',tasks,summary:{total:n}});let outcome='VERIFIED',release,hold=false;
 const flow={store:source,runtime:dir,artifacts:dir,active:null,submits:0,
  launch(id){this.active=id;this.stopping=false;this.pending=(async()=>{const r=source.run(id),unknown=r.state==='RESULT_UNKNOWN';if(!unknown)source.move(id,'RUNNING');if(hold)await new Promise(resolve=>release=resolve);if(this.stopping){source.move(id,'PAUSED','操作者暂停');return;}if(outcome==='VERIFIED'){if(!unknown){source.move(id,'SUBMITTING');this.submits++;}source.move(id,'VERIFIED','',result(id));}else source.move(id,outcome,outcome==='PAUSED_CAPTCHA'?'PAUSED_CAPTCHA':'ordinary failure');})().finally(()=>this.active=null);},
  async resume({id}){const r=source.run(id);if(r.state!=='RESULT_UNKNOWN')source.move(id,'QUEUED');this.launch(id);},pause(){this.stopping=true;release?.();}};
 const batch=new BatchWorkflow(flow);const create=(count=n)=>batch.create({importId,limit:count,mode:'LIVE',review:{reviewed:true,selectionHash:batch.preview(importId,count).selectionHash,authorization:'test fixture'}},shop);
 return {dir,source,tasks,flow,batch,create,importId,setOutcome:v=>outcome=v,hold:()=>hold=true,release:()=>{hold=false;release?.();}};
}
test('20 frozen tasks run once, stop at the cap, retain unique task IDs and results',async t=>{const x=await fixture(t,25),b=x.create(20);x.batch.start(b.id,shop);await x.batch.pending;const v=x.batch.store.view(b.id);assert.equal(v.counts.SUCCEEDED,20);assert.equal(v.state,'COMPLETED');assert.equal(x.flow.submits,20);assert.equal(x.source.list().length,20);assert.equal(new Set(v.items.map(i=>i.id)).size,20);assert.throws(()=>x.batch.start(b.id,shop),/结束/);});
test('wrong selection hash, duplicate destinations and cap overflow create no queue',async t=>{const x=await fixture(t);assert.throws(()=>x.batch.create({importId:x.importId,limit:21,mode:'LIVE'},shop),/20/);assert.throws(()=>x.batch.create({importId:x.importId,mode:'LIVE',review:{selectionHash:'stale'}},shop),/改变/);assert.equal(x.batch.store.batch(),null);});
test('CAPTCHA pauses the entire batch and manual continue resumes original run',async t=>{const x=await fixture(t),b=x.create();x.setOutcome('PAUSED_CAPTCHA');x.batch.start(b.id,shop);await x.batch.pending;let v=x.batch.store.view(b.id);assert.equal(v.counts.WAITING_HUMAN,1);assert.equal(v.counts.PENDING,2);assert.equal(x.flow.submits,0);const id=v.items[0].runId;x.setOutcome('VERIFIED');x.batch.start(b.id,shop);await x.batch.pending;v=x.batch.store.view(b.id);assert.equal(v.items[0].runId,id);assert.equal(v.items[0].attempts,1);assert.equal(v.counts.SUCCEEDED,3);});
test('failures are finite: manual retries cannot exceed three attempts',async t=>{const x=await fixture(t,1),b=x.create();x.setOutcome('PAUSED');x.batch.start(b.id,shop);await x.batch.pending;assert.equal(x.batch.store.view(b.id).counts.FAILED,1);for(let n=0;n<2;n++){x.batch.retry(b.id,shop);await x.batch.pending;}assert.equal(x.batch.store.view(b.id).items[0].attempts,3);assert.throws(()=>x.batch.retry(b.id,shop),/上限/);assert.equal(x.flow.submits,0);});
test('pause during a step prevents later tasks and concurrent start is rejected',async t=>{const x=await fixture(t),b=x.create();x.hold();x.batch.start(b.id,shop);assert.throws(()=>x.batch.start(b.id,shop),/已有/);x.batch.pause();x.release();await x.batch.pending;const v=x.batch.store.view(b.id);assert.equal(v.state,'PAUSED');assert.equal(v.counts.PENDING,2);assert.equal(x.flow.submits,0);});
test('program restart reconciles successful run without a second publish',async t=>{const x=await fixture(t,1),b=x.create(),i=x.batch.store.items(b.id)[0];x.batch.store.claim(i.id);const r=x.source.create(x.importId,i.task,'LIVE','SOURCE',{reviewed:true,taskHash:digest(i.task)});x.batch.store.attach(i.id,r.id);x.source.move(r.id,'RUNNING');x.source.move(r.id,'SUBMITTING');x.source.move(r.id,'VERIFIED','',result(r.id));const reopened=new BatchStore(x.source);reopened.recover();assert.equal(reopened.item(i.id).state,'SUCCEEDED');assert.throws(()=>reopened.move(i.id,'RETRY'),/禁止/);});
test('crash after submit preserves result-unknown and only reconciles, never resubmits',async t=>{const x=await fixture(t,1),b=x.create(),i=x.batch.store.items(b.id)[0];x.batch.store.claim(i.id);x.batch.store.setBatch(b.id,'RUNNING');const r=x.source.create(x.importId,i.task,'LIVE','SOURCE',{reviewed:true,taskHash:digest(i.task)});x.batch.store.attach(i.id,r.id);x.source.move(r.id,'RUNNING');x.source.move(r.id,'SUBMITTING');x.source.checkpoint(r.id,{itemId:'10001'});x.source.recover();const recovered=new BatchWorkflow(x.flow);assert.equal(recovered.store.item(i.id).state,'WAITING_HUMAN');assert.throws(()=>recovered.skip(b.id,i.id),/禁止跳过/);recovered.start(b.id,shop);await recovered.pending;assert.equal(x.flow.submits,0);assert.equal(recovered.store.item(i.id).state,'SUCCEEDED');});
test('success history is excluded across reordered imports and title versions',async t=>{const x=await fixture(t),b=x.create();x.batch.start(b.id,shop);await x.batch.pending;const tasks=x.tasks.map(t=>({...t,priority:100+t.priority,listing:{...t.listing,title:'different'}})),id=x.source.imported({sheet:'境外城市热度',tasks,sourceHash:'new'});assert.equal(x.batch.preview(id).tasks.length,0);assert(x.batch.preview(id).excluded.every(x=>x.reason==='已有成功记录'));});
test('explicit skipped state never dispatches that destination',async t=>{const x=await fixture(t),b=x.create(),i=x.batch.store.items(b.id)[0];x.batch.skip(b.id,i.id,'excluded by reviewer');x.batch.start(b.id,shop);await x.batch.pending;assert.equal(x.batch.store.view(b.id).counts.SKIPPED,1);assert.equal(x.flow.submits,2);});
test('skipping all pending tasks finishes the batch without submissions',async t=>{const x=await fixture(t),b=x.create();for(const i of x.batch.store.items(b.id))x.batch.skip(b.id,i.id,'review exclusion');assert.equal(x.batch.store.view(b.id).state,'COMPLETED');assert.equal(x.flow.submits,0);});
