import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../travel-os.js',import.meta.url),'utf8');
const projection=source.slice(source.indexOf('const overviewGroups='),source.indexOf('function overviewSnapshot()'));
function project(snapshot){const context=vm.createContext({snapshot});vm.runInContext(projection,context);return JSON.parse(JSON.stringify(vm.runInContext('overviewSummary(snapshot)',context)));}
const product=(id,state='AVAILABLE')=>({key:id,geoKey:id,shopId:'shop',destination:id,runId:id,state});
const base=()=>({products:[],attempts:[],engine:{shop:{id:'shop'},active:null,exceptions:[],batches:[],batch:{id:'b',mode:'LIVE',total:0,items:[],counts:{}}}});
test('counts unique shop-products and current verified products, not attempts',()=>{const s=base();s.products=[product('a','VERIFIED'),product('a','VERIFIED'),product('b')];s.attempts=[{id:'old'},{id:'a'}];const p=project(s);assert.equal(p.products.length,2);assert.equal(p.verified,1);});
test('queue failure overrides generic PAUSED without treating it as a captcha',()=>{const s=base();s.products=[product('a','PAUSED')];s.engine.exceptions=[{id:'a',state:'PAUSED'}];s.engine.batch.items=[{id:'t',runId:'a',state:'FAILED',displayState:'FAILED'}];const p=project(s);assert.equal(p.attention.length,1);assert.equal(p.groups.failed.length,1);assert.equal(p.groups.captcha.length,0);});
test('data and operational issues union by product, standalone data products are included',()=>{const s=base();s.products=[product('a','NEEDS_DATA'),product('b','NEEDS_DATA')];s.engine.exceptions=[{id:'a',state:'PAUSED',retryable:true},{id:'data',dataOnly:true}];const p=project(s);assert.equal(p.attention.length,2);assert.equal(p.groups.data.length,1);assert.equal(p.groups.failed.length,1);});
test('superseded failures of a verified product are not current problems',()=>{const s=base();s.products=[product('a','VERIFIED')];s.attempts=[{id:'old',shopId:'shop',geoKey:'a'}];s.engine.exceptions=[{id:'old',state:'PAUSED',retryable:true}];assert.equal(project(s).attention.length,0);});
test('captcha, ambiguous result and pause have distinct categories',()=>{const s=base();s.products=['a','b','c'].map(id=>product(id,'PAUSED'));s.engine.exceptions=[{id:'a',state:'PAUSED_CAPTCHA',captcha:true},{id:'b',state:'RESULT_UNKNOWN',unknown:true},{id:'c',state:'PAUSED'}];const p=project(s);assert.equal(p.groups.captcha.length,1);assert.equal(p.groups.unknown.length,1);assert.equal(p.groups.paused.length,1);assert.equal(p.groups.failed.length,0);});
test('dry-run completion is neither captcha nor verified publication',()=>{const s=base();s.products=[product('a','DRY_RUN_COMPLETE')];s.engine.exceptions=[{id:'a',state:'DRY_RUN_COMPLETE'}];s.engine.batch={mode:'DRY_RUN',total:1,items:[{runId:'a',state:'WAITING_HUMAN',runState:'DRY_RUN_COMPLETE'}],counts:{WAITING_HUMAN:1}};const p=project(s);assert.equal(p.attention.length,0);assert.equal(p.progress.success,0);assert.equal(p.progress.dry,1);assert.equal(p.progress.processed,1);});
test('completed processing shows success, failures and skipped separately',()=>{const s=base();s.engine.batch={mode:'LIVE',total:4,items:[{state:'SUCCEEDED',runState:'VERIFIED'},{state:'SUCCEEDED',runState:'VERIFIED'},{state:'FAILED'},{state:'SKIPPED'}],counts:{SUCCEEDED:2,FAILED:1,SKIPPED:1}};const p=project(s).progress;assert.equal(p.processed,4);assert.equal(p.success,2);assert.equal(p.failed,1);assert.equal(p.skipped,1);});
test('an ambiguous queued failure is not counted as a completed failure',()=>{const s=base();s.engine.batch={mode:'LIVE',total:1,items:[{id:'t',runId:'a',state:'FAILED',displayState:'RESULT_UNKNOWN',runState:'RESULT_UNKNOWN'}],counts:{FAILED:1}};const p=project(s);assert.equal(p.progress.failed,0);assert.equal(p.progress.processed,0);assert.equal(p.groups.unknown.length,1);});
test('standalone failure omitted by old exception adapter still appears',()=>{const s=base();s.products=[product('a','FAILED')];s.attempts=[{id:'a',geoKey:'a',shopId:'shop',state:'FAILED'}];assert.equal(project(s).groups.failed.length,1);});
test('empty libraries and missing batch produce real zero and empty states',()=>{const s=base();s.engine.batch=null;const p=project(s);assert.equal(p.products.length,0);assert.equal(p.verified,0);assert.equal(p.attention.length,0);assert.equal(p.progress.total,0);assert.equal(p.waitingBatches.length,0);});

test('generic WAITING_HUMAN is not falsely labelled as a captcha',()=>{const s=base();s.engine.batch.items=[{id:'t',runId:'a',state:'WAITING_HUMAN',issue:{category:'恢复检查'}}];const p=project(s);assert.equal(p.groups.captcha.length,0);assert.equal(p.groups.paused.length,1);});

test('paused batch with pending retry is counted as waiting to continue',()=>{const s=base();s.engine.batch={id:'b',mode:'LIVE',state:'PAUSED',total:1,items:[{id:'t',runId:'a',state:'RETRY'}],counts:{RETRY:1}};s.engine.batches=[{id:'b',state:'PAUSED'}];assert.equal(project(s).waitingBatches.length,1);});
