// Fully isolated UI + seller-list fixture. No production profile or external request.
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm,copyFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,join,dirname} from 'node:path';
import {createServer} from 'node:http';
import {chromium} from 'playwright';
import {SourceStore,digest} from '../source-store.mjs';
import {BatchWorkflow} from '../batch-workflow.mjs';
import {ProductApi} from '../product-api.mjs';
import {TravelOsApi} from '../travel-os-api.mjs';
import {createStaticHandler} from '../static-files.mjs';
const root=resolve(import.meta.dirname,'..'),out=resolve(process.env.QA_OUTPUT_DIR||join(root,'../output/playwright/reconciliation-'+Date.now()));
await mkdir(out,{recursive:true});const dir=await mkdtemp(join(tmpdir(),'travel-reconcile-ui-')),store=new SourceStore(join(dir,'state.sqlite'));
const shop={id:'isolated-review',name:'隔离核验店铺'},itemId='1088061246413',sellerUrl='https://myseller.taobao.com/home.htm/SellManage/all';
const tasks=[1,2].map(n=>({shopId:shop.id,priority:n,source:{sheet:'境外城市热度'},listing:{type:'city',country:'测试国家',city:'测试城市'+n,title:'测试旅游商品'+n},business:{shop_name:shop.name,price_cny:20,inventory:100},assets:{main:[],secondary:[],details:[]},adapterIssues:[]}));
const imported=store.imported({sheet:'境外城市热度',sourceHash:'RECONCILE_FIXTURE',tasks});
let launches=0;
const flow={store,active:null,runtime:dir,artifacts:join(dir,'artifacts'),pause(){this.stop=true;},launch(){launches++;throw Error('MUST_NOT_EXECUTE');}},batch=new BatchWorkflow(flow);
const b=batch.create({importId:imported,limit:2,mode:'LIVE',review:{reviewed:true,selectionHash:batch.preview(imported,2).selectionHash,authorization:'isolated test only'}},shop),first=batch.store.items(b.id)[0];
batch.store.claim(first.id);const run=store.create(imported,tasks[0],'LIVE','SOURCE',{reviewed:true,taskHash:digest(tasks[0])});batch.store.attach(first.id,run.id);
store.move(run.id,'RUNNING');store.move(run.id,'SUBMITTING');store.move(run.id,'RESULT_UNKNOWN','隔离提交结果不明');batch.store.move(first.id,'WAITING_HUMAN');batch.store.setBatch(b.id,'WAITING_HUMAN');
store.event(run.id,'STEP_VERIFIED',{name:'title',screenshot:join(flow.artifacts,run.id,'old.png')});
store.event(run.id,'STEP_PAUSED',{name:'verify-platform-result',screenshot:null,screenshotError:'ISOLATED_SCREENSHOT_FAILED'});
store.checkpoint(run.id,{screenshot:null,screenshotError:'ISOLATED_SCREENSHOT_FAILED'});
const created=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());
const owner={sessions:new Map(),status:async()=>({running:true,loggedIn:true,loginState:'LOGGED_IN',checkedAt:new Date().toISOString()})};
const product=new ProductApi({source:flow,batch,owner,shop,runtime:dir,integrity:async()=>({ok:true,files:11}),checkFiles:async()=>{},launch:async()=>{throw Error('NO_BROWSER_LAUNCH');}});
const os=new TravelOsApi({product:async()=>product,shops:async()=>[shop],browser:owner,runtime:dir,launch:async()=>{throw Error('NO_BROWSER_LAUNCH');}});
const requests=[],external=[],checks=[],errors=[],apiErrors=[];const check=(ok,label)=>{assert(ok,label);checks.push(label);};
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(data));};
const body=async req=>{let data='';for await(const b of req)data+=b;const value=JSON.parse(data||'{}');requests.push({path:req.url,body:value});return value;};
const serve=createStaticHandler(root),server=createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/os/state')return json(res,200,{...await os.snapshot(),testMode:true});if(u.pathname.startsWith('/api/os/'))return await os.handle(req,res,u,{json,body});if(u.pathname.startsWith('/api/v1/'))return await product.handle(req,res,u,{json,body});await serve(req,res);}catch(e){apiErrors.push(e.message);json(res,e.statusCode||409,{error:e.message});}});
let browser;
try{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({channel:'chrome',headless:true});
 const seller=await browser.newContext({serviceWorkers:'block'});
 const fixture=`<!doctype html><html><head><meta charset="utf-8"></head><body><div class="shopName--x6nyUylx">${shop.name}</div><button role="tab" aria-selected="true">全部(1)</button><input id="queryTitle"><input id="queryItemId"><button onclick="document.querySelector('tbody').hidden=false">搜索</button><table><thead><tr><th>商品名称</th><th>价格</th><th>库存</th><th>创建时间</th></tr></thead><tbody hidden><tr><td>${tasks[0].listing.title}<br>ID:${itemId}</td><td id="fixturePrice">¥ 120.00</td><td>100</td><td>${created}<br>出售中</td></tr></tbody></table></body></html>`;
 await seller.route('**/*',route=>{if(route.request().url()===sellerUrl)return route.fulfill({contentType:'text/html; charset=utf-8',body:fixture});external.push(route.request().url());return route.abort();});
 owner.sessions.set(shop.id,{context:seller});const sellerPage=await seller.newPage();await sellerPage.goto(sellerUrl);
 const ui=await browser.newContext({viewport:{width:1440,height:900},serviceWorkers:'block'});
 await ui.route('**/*',route=>{if(new URL(route.request().url()).origin===base)return route.continue();external.push(route.request().url());return route.abort();});
 const page=await ui.newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));
 const legacy=await ui.newPage();legacy.setDefaultTimeout(10000);await legacy.goto(base+'/index.html#monitor');
 await legacy.locator('#monitorImage').getByText('本次截图未保存',{exact:true}).waitFor();
 check(await legacy.locator('#monitorImage img').count()===0,'旧监控明确提示本次截图失败，不回退显示旧步骤图片');
 await legacy.screenshot({path:join(out,'06-missing-screenshot-legacy.png')});await legacy.close();
 await page.goto(base+'/travel-os.html#records');await page.locator('.records-actions [data-action=record-detail]').first().click();
 await page.locator('#editorBody').getByText('本次截图未保存：ISOLATED_SCREENSHOT_FAILED',{exact:true}).first().waitFor();
 check((await page.locator('#editorBody').innerText()).includes('本次截图未保存'),'执行证据弹窗展示截图失败原因');
 await page.screenshot({path:join(out,'07-missing-screenshot-detail.png')});await page.locator('#closeEditor').click();
 await page.goto(base+'/travel-os.html#tasks');await page.locator('[data-action=continue]').click();check((await page.locator('#editorBody').innerText()).includes('商品 ID'),'原恢复窗口先说明缺失商品 ID');await page.locator('#editorBody').getByRole('button',{name:'关联原商品并核验',exact:true}).click();
 check((await page.locator('#associateResultForm').innerText()).includes('剩余任务不会自动执行'),'关联窗口明确只核验原商品');
 await page.screenshot({path:join(out,'01-associate-dialog.png')});
 await page.setViewportSize({width:390,height:844});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'390px 关联窗口无横向溢出');
 await page.screenshot({path:join(out,'02-associate-mobile.png')});await page.setViewportSize({width:1440,height:900});
 await page.locator('#associateResultForm [name=itemId]').fill(itemId);await page.locator('#associateResultForm [name=confirmed]').check();
 await page.locator('#associateResultForm button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#editorError').textContent.includes('价格'));
 check(store.run(run.id).state==='RESULT_UNKNOWN'&&store.completed(tasks[0])===null,'真实查询解析拒绝错误价格；不保存成功');
 await page.screenshot({path:join(out,'03-price-mismatch.png')});
 await sellerPage.locator('#fixturePrice').evaluate(el=>el.textContent='¥ 20.00');
 await page.locator('#associateResultForm button[type=submit]').click();await page.locator('#editor').waitFor({state:'hidden'});
 check(store.run(run.id).checkpoint.screenshot===store.run(run.id).result.screenshot&&!store.run(run.id).checkpoint.screenshotError,'关联成功后当前截图指向新核验证据');
 check(store.run(run.id).state==='VERIFIED','真实核验模块解析本地卖家样式页并保存原任务结果');
 check(batch.store.item(first.id).state==='SUCCEEDED'&&batch.store.items(b.id)[1].state==='PENDING'&&batch.store.batch(b.id).state==='PAUSED','队列只回写本条，余下任务保持暂停');
 check(launches===0,'没有调用执行器或提交商品');check((await product.settings()).executionEnabled===false,'执行关闭状态不变');
 await page.screenshot({path:join(out,'04-reconciled-paused.png')});
 const request=requests.filter(r=>r.path==='/api/v1/reconcile').at(-1);
 const replay=await ui.request.post(base+'/api/v1/reconcile',{data:request.body});check((await replay.json()).replayed===true,'成功响应丢失后同一请求安全重放');
 check(store.events(run.id).filter(e=>e.kind==='VERIFIED').length===1&&store.db.prepare('SELECT COUNT(*) n FROM history').get().n===1,'成功历史和事件只写一次');
 await page.reload();await page.locator('[data-action=continue]').waitFor();check(await page.getByRole('button',{name:'关联原商品并核验',exact:true}).count()===0,'刷新后成功记录持久保留，关联入口收起');
 await copyFile(store.run(run.id).result.screenshot,join(out,'05-synthetic-seller-evidence.png'));
 check(errors.length===0&&external.length===0,'无浏览器异常，无外部网络请求');
}finally{
 await writeFile(join(out,'result.json'),JSON.stringify({at:new Date().toISOString(),checks,errors,apiErrors,external,launches,requests,productionSubmissions:0,scope:'Synthetic seller DOM + real local APIs, no real account or platform acceptance'},null,2));
 console.log(JSON.stringify({checks:checks.length,errors,apiErrors,external,launches}));await browser?.close();product.closeStreams();await new Promise(r=>{server.close(r);server.closeAllConnections();});os.store.close();store.close();assert.equal(dirname(resolve(dir)),resolve(tmpdir()));await rm(dir,{recursive:true,force:true});
}
