import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,dirname,resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {TravelOsStore,geoKey} from '../travel-os-store.mjs';
import {TravelOsApi} from '../travel-os-api.mjs';
import {SourceStore,digest} from '../source-store.mjs';
import {BatchWorkflow} from '../batch-workflow.mjs';
import {ProductApi} from '../product-api.mjs';
const place={key:'original-product',type:'city',country:'测试国',city:'测试城',destination:'测试城',shopId:'test-shop',title:'测试商品',source:{},state:'AVAILABLE'};
const quote=(patch={})=>({requestId:randomUUID(),kind:'COST',service:'测试服务',amount:'100.25',currency:'CNY',unit:'天',supplier:'测试供应商',validUntil:'2026-12-31',...patch});
function memory(t){const s=new TravelOsStore(':memory:');t.after(()=>s.close());return s;}
test('cost and sale quotes share geography but remain separate immutable records',t=>{const s=memory(t);const a=s.addQuote(quote(),place),b=s.addQuote(quote({kind:'SALE',amount:'150',supplier:''}),place);assert.equal(a.destinationKey,b.destinationKey);assert.equal(s.quotes(geoKey(place)).length,2);assert.equal(s.quotes()[0].kind,'SALE');s.archiveQuote(a.id);assert.equal(s.quotes().length,2);assert.equal(s.quotes().find(x=>x.id===a.id).archived,true);});
test('double submitted quote has one durable result, reused id cannot change payload',t=>{const s=memory(t),input=quote();const a=s.addQuote(input,place),b=s.addQuote(input,place);assert.equal(a.id,b.id);assert.equal(s.quotes().length,1);assert.throws(()=>s.addQuote({...input,amount:30},place),/编号/);});
test('quote validation rejects invented destination, missing supplier and invalid money/date',t=>{const s=memory(t);assert.throws(()=>s.addQuote(quote(),null),/目的地/);for(const patch of [{kind:'fake'},{amount:0},{amount:Infinity},{amount:0.001},{supplier:''},{unit:''},{currency:'XXX'},{validUntil:'2026-13-22'},{validUntil:'2026-02-30'}])assert.throws(()=>s.addQuote(quote(patch),place));assert.equal(s.quotes().length,0);});
test('preparations cannot duplicate successful, occupied or open work',t=>{const s=memory(t),input={requestId:randomUUID()},shop={id:'test-shop'};assert.throws(()=>s.prepare(input,{...place,state:'VERIFIED'},shop),/成功/);assert.throws(()=>s.prepare(input,{...place,duplicateBlocked:true},shop),/已有任务/);const a=s.prepare(input,place,shop);assert.equal(s.prepare(input,place,shop).id,a.id);assert.throws(()=>s.prepare({requestId:randomUUID()},place,shop),/已有同商品/);s.cancelPreparation(a.id);assert.equal(s.preparations()[0].state,'CANCELLED');s.prepare({requestId:randomUUID()},place,shop);assert.equal(s.preparations().length,2);});
test('removing a managed shop preserves quote history and cancels only preparations',t=>{const s=memory(t);s.addQuote(quote(),place);s.prepare({requestId:randomUUID()},place,{id:'test-shop'});s.removeShop('test-shop');assert(s.removed('test-shop'));assert.equal(s.preparations()[0].state,'CANCELLED');assert.equal(s.quotes().length,1);});
test('product data and idempotent result survive service-store restart',async t=>{const dir=await mkdtemp(join(tmpdir(),'travel-os-persist-'));t.after(async()=>{assert.equal(dirname(resolve(dir)),resolve(tmpdir()));await rm(dir,{recursive:true,force:true});});const file=join(dir,'os.sqlite'),input=quote();let s=new TravelOsStore(file);const q=s.addQuote(input,place);s.prepare({requestId:randomUUID()},place,{id:'test-shop'});s.close();s=new TravelOsStore(file);assert.equal(s.addQuote(input,place).id,q.id);assert.equal(s.preparations().length,1);s.close();});
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'travel-os-api-'));const store=new SourceStore(join(dir,'source.sqlite')),task={shopId:'test-shop',priority:1,source:{sheet:'商品资料',row:2},listing:{type:'city',country:'测试国',city:'测试城',title:'测试商品'},business:{price_cny:20,inventory:2},assets:{main:[],secondary:[],details:[]},adapterIssues:[]};const flow={store,active:null,submits:0,artifacts:dir,pause(){},launch(){throw Error('QA 禁止执行浏览器');}},batch=new BatchWorkflow(flow),shop={id:'test-shop',name:'QA 店铺'},shops=[shop],owner={sessions:new Map(),status:async()=>({running:false,loggedIn:false,loginState:'LOGIN_REQUIRED'})},p=new ProductApi({source:flow,batch,shop,owner,runtime:dir,launch:()=>{throw Error('禁止启动浏览器');},integrity:async()=>({ok:true}),checkFiles:async()=>{}});const importId=store.imported({sheet:'商品资料',sourceHash:'test',tasks:[task]});const api=new TravelOsApi({product:async()=>p,shops:async()=>shops,browser:owner,launch:()=>{throw Error('禁止启动浏览器');},runtime:dir,addShop:async name=>{const s={id:randomUUID(),name};shops.push(s);return s;}});t.after(async()=>{api.store.close();store.close();assert.equal(dirname(resolve(dir)),resolve(tmpdir()));await rm(dir,{recursive:true,force:true});});const call=async(action,input)=>{let result;await api.handle({method:input?'POST':'GET'},{},new URL('/api/os/'+action,'http://localhost'),{body:async()=>input,json:(r,status,data)=>result={status,data}});return result;};return {dir,store,task,flow,batch,p,shops,api,call,importId};}
test('state projection does not reveal credentials or pretend a new shop can execute',async t=>{const x=await fixture(t);await x.call('shops/add',{name:'新 QA 店铺'});const {data:s}=await x.call('state');assert.equal(s.shops.length,2);assert.equal(s.shops[1].executionSupported,false);assert.equal(s.shops[1].browser.label,'待检查');assert(!JSON.stringify(s.shops).includes('profileDir'));assert.equal(x.flow.submits,0);});
test('shop deletion is blocked by prepared execution batch, leaves all data intact',async t=>{const x=await fixture(t);x.batch.store.create(x.importId,[x.task],'test-shop','DRY_RUN',{reviewed:true,selectionHash:digest([x.task]),authorization:'QA'});await assert.rejects(x.call('shops/remove',{shopId:'test-shop',confirmName:'QA 店铺'}),/任务|核验/);assert.equal(x.api.store.removed('test-shop'),false);});
test('selected destination preserves original snapshot, DRY_RUN queue only and duplicate barrier',async t=>{const x=await fixture(t);const {products}=await x.api.catalog(),input={productKey:products[0].key,shopId:'test-shop'},preview=await x.api.selectedPreview(input);assert.deepEqual(preview.task,x.task);await assert.rejects(x.call('selected-create',{...input,mode:'LIVE',review:{}}),/DRY_RUN/);await assert.rejects(x.call('selected-create',{...input,mode:'DRY_RUN',review:{reviewed:true,selectionHash:'stale'}}),/变化/);await x.call('selected-create',{...input,mode:'DRY_RUN',review:{reviewed:true,selectionHash:preview.selectionHash,authorization:'QA'}});assert.equal(x.batch.store.view().counts.PENDING,1);assert.equal(x.flow.submits,0);await assert.rejects(x.api.selectedPreview(input),/已有任务/);});
test('selected destination rejects existing single run and successful history',async t=>{const x=await fixture(t);const {products}=await x.api.catalog(),input={productKey:products[0].key,shopId:'test-shop'};x.store.create(x.importId,x.task,'DRY_RUN','SOURCE',{reviewed:true,taskHash:digest(x.task)});await assert.rejects(x.api.selectedPreview(input),/已有任务/);x.store.history(x.task,{itemId:'QA-ONLY'});await assert.rejects(x.api.selectedPreview(input),/成功/);});
test('selected destination refuses retargeting original product to a new shop',async t=>{const x=await fixture(t);const {data:shop}=await x.call('shops/add',{name:'新店'});const {products}=await x.api.catalog();await assert.rejects(x.api.selectedPreview({productKey:products[0].key,shopId:shop.id}),/店铺|适配/);});
test('unknown submission cannot be skipped through product adapter',async t=>{const x=await fixture(t);const b=x.batch.store.create(x.importId,[x.task],'test-shop','LIVE',{reviewed:true,selectionHash:digest([x.task]),authorization:'QA'}),item=x.batch.store.items(b.id)[0],run=x.store.create(x.importId,x.task,'LIVE','SOURCE',{reviewed:true,taskHash:digest(x.task)});x.batch.store.attach(item.id,run.id);x.batch.store.claim(item.id);x.store.move(run.id,'RUNNING');x.store.move(run.id,'SUBMITTING');x.store.move(run.id,'RESULT_UNKNOWN','QA unknown');x.batch.store.move(item.id,'WAITING_HUMAN');await assert.rejects(x.call('batch/skip',{id:b.id,taskId:item.id,reason:'QA'}),/不能跳过/);assert.equal(x.batch.store.item(item.id).state,'WAITING_HUMAN');});
