// Product-layer QA. A separate headless Chrome; every write API is blocked.
import {chromium,expect} from 'playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
const base='http://127.0.0.1:4318',out=process.env.TRAVEL_HOME_QA_OUTPUT?resolve(process.env.TRAVEL_HOME_QA_OUTPUT)+'/':fileURLToPath(new URL('../../output/travel-home-20260923/',import.meta.url));await mkdir(out,{recursive:true});
const before=await fetch(base+'/api/v1/state').then(r=>r.json()),catalog=await fetch(base+'/api/v1/destinations?limit=100').then(r=>r.json());
assert.equal(before.active,null);assert.equal(before.settings.executionEnabled,false);
const browser=await chromium.launch({channel:'chrome',headless:true}),checks=[],errors=[],writes=[],layouts=[];
const guard=async page=>{page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/**',async route=>{if(route.request().method()!=='GET'){writes.push(route.request().url());return route.abort();}return route.continue();});};
const noOverflow=async page=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
try{
 const page=await browser.newPage({viewport:{width:1672,height:941}});await guard(page);
 await page.goto(base);await expect(page.locator('.city-name')).toHaveText('东京');await expect(page.locator('#serviceState')).toContainText('本地服务正常');await expect(page.locator('.operations')).toHaveCount(0);await expect(page.locator('.metrics,.map-summary')).toHaveCount(0);await noOverflow(page);
 await page.evaluate(()=>Promise.all([...document.images].filter(x=>x.loading!=='lazy').map(x=>x.decode().catch(()=>{}))));
 await page.screenshot({path:out+'desktop.png'});await page.screenshot({path:out+'desktop-full.png',fullPage:true});checks.push('homepage uses actual catalogue and service state; operational tables stay in workspace');
 await page.locator('#citySearch').fill('东京');await expect(page.locator('.result-row').first()).toContainText('东京');await page.locator('#citySearch').press('ArrowDown');await page.keyboard.press('Enter');await expect(page.locator('#searchResults')).toBeHidden();await expect(page.locator('.city-name')).toHaveText('东京');checks.push('keyboard city search and selection');
 await page.getByRole('button',{name:'查看资料与素材'}).click();await expect(page.locator('#materialDialog')).toBeVisible();await expect(page.locator('.materials-grid figure')).toHaveCount(13);
 await page.locator('.materials-grid img').evaluateAll(imgs=>imgs.forEach(i=>i.loading='eager'));await page.waitForFunction(()=>[...document.querySelectorAll('.materials-grid img')].every(x=>x.complete&&x.naturalWidth>0));
 await page.screenshot({path:out+'tokyo-materials.png'});await page.getByRole('button',{name:'关闭资料'}).click();checks.push('Tokyo original material preview uses existing hash-checked asset endpoint');
 await page.locator('.card-next').click();await expect(page.locator('#recordSearch')).toHaveValue('东京');await expect(page.locator('#recordTable tbody tr')).toHaveCount(1);await expect(page.locator('#recordTable')).toContainText('东京');assert.equal(await page.locator('#recordTable').getByText('禁止重复上架').count(),1);checks.push('Tokyo record deep link filters existing workbench');
 await page.getByRole('link',{name:'返回星途首页'}).click();await expect(page.locator('.city-name')).toHaveText('东京');
 await page.locator('#citySearch').fill('伦敦');await page.locator('#citySearch').press('Enter');await expect(page.locator('.city-name')).toHaveText('伦敦');assert.equal(await page.locator('.city-backdrop').count(),0);await page.getByRole('button',{name:'查看资料与素材'}).click();await expect(page.locator('.material-issues')).toContainText('目的地不一致');await page.getByRole('button',{name:'关闭资料'}).click();checks.push('material issues remain accessible by search; mismatched image is not used as decoration');
 await page.locator('#citySearch').fill('不存在的目的地xyz');await page.getByRole('button',{name:'搜索目的地',exact:true}).click();await expect(page.locator('.result-summary')).toContainText('没有匹配');await page.locator('#citySearch').press('Escape');await expect(page.locator('#searchResults')).toBeHidden();checks.push('no-result search and escape');
  await page.locator('#citySearch').fill('东京');await page.getByRole('button',{name:'搜索目的地',exact:true}).click();await expect(page.locator('.city-name')).toHaveText('东京');await page.reload();await expect(page.locator('.city-name')).toHaveText('东京');checks.push('selected destination survives refresh without execution');
 await expect(page.locator('#homeAttention')).toBeHidden();checks.push('no invented urgent task banner when backend has no intervention');
 await page.locator('#quickCities button').filter({hasText:'东京'}).click();await expect(page.locator('.city-name')).toHaveText('东京');
 await page.getByRole('button',{name:'使用帮助',exact:true}).click();await expect(page.locator('#helpDialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#helpDialog')).toBeHidden();checks.push('help dialog keyboard close');
 await page.getByRole('link',{name:'打开工作台',exact:true}).click();await expect(page).toHaveURL(/travel-os\.html#overview$/);await expect(page.locator('#navigation a')).toHaveCount(8);await page.getByRole('link',{name:'返回星途首页',exact:true}).first().click();await expect(page.locator('.city-name')).toHaveText('东京');checks.push('original homepage enters eight-module workspace only through navigation and can return');
 await page.getByRole('button',{name:'使用帮助',exact:true}).click();await page.locator('#helpDialog').getByRole('link',{name:'导入商品资料',exact:true}).click();await expect(page).toHaveURL(/index\.html\?portal=import#tasks$/);await expect(page.locator('#importDialog')).toBeVisible();await expect(page.locator('#recognize')).toBeVisible();await page.getByRole('button',{name:'关闭导入'}).click();checks.push('existing import route opens the upload dialog without submitting; entry remains outside the visual hero');
 await page.goto(base+'/#records');await expect(page).toHaveURL(/index\.html#records$/);await expect(page.locator('#recordSearch')).toBeVisible();checks.push('legacy root hash links remain compatible');
 for(const [width,height]of [[2552,1274],[1672,941],[1440,900],[1920,1080],[1366,768],[1280,720],[1366,640],[1024,640],[1024,768],[1024,900],[768,1024],[390,844],[360,780]]){await page.setViewportSize({width,height});await page.goto(base);await expect(page.locator('.city-name')).toHaveText('东京');await noOverflow(page);if(width>=951){await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight)).toBe(true);for(const selector of ['.header','.primary-actions','footer','.globe-tools'])await expect(page.locator(selector)).toBeInViewport({ratio:1});const limits=await page.evaluate(()=>({header:document.querySelector('.header').getBoundingClientRect().bottom,footer:document.querySelector('footer').getBoundingClientRect().top,content:[...document.querySelectorAll('.hero h1,#searchForm,.city-card,.primary-actions')].map(el=>({selector:el.className,top:el.getBoundingClientRect().top,bottom:el.getBoundingClientRect().bottom}))}));for(const r of limits.content){assert(r.top>=limits.header-1,JSON.stringify({width,height,r,limits}));assert(r.bottom<=limits.footer+1,JSON.stringify({width,height,r,limits}));}}layouts.push(await page.evaluate(()=>({width:innerWidth,height:innerHeight,pageWidth:document.documentElement.scrollWidth,pageHeight:document.documentElement.scrollHeight})));await page.screenshot({path:out+`home-${width}x${height}.png`,fullPage:width<1000});checks.push('layout '+width+'x'+height);}
 await page.setViewportSize({width:390,height:844});await page.locator('#citySearch').fill('东京');await page.getByRole('button',{name:'搜索目的地',exact:true}).click();await expect(page.locator('.city-name')).toHaveText('东京');checks.push('mobile search interaction');
 const fake=await browser.newPage({viewport:{width:1440,height:1000}});await guard(fake);
 const fixtureState={testMode:true,at:new Date().toISOString(),shop:{name:'隔离测试店铺'},browser:{label:'待检查',loggedIn:false},settings:{executionEnabled:false},execution:{state:'IDLE'},overview:{published:0},exceptions:[],records:[],batch:null,active:null};
 const fixtureCity={key:'fixture-city',destination:'测试目的地',country:'测试国家',city:'测试目的地',type:'city',title:'隔离测试商品',rank:1,source:{name:'fixture.xlsx',sheet:'测试',row:2,importedAt:new Date().toISOString()},issues:[],materials:[],counts:{main:0,secondary:0,details:0},state:'RESULT_UNKNOWN',stateLabel:'待核验',reason:'提交结果不明确',duplicateBlocked:true,next:{label:'查看处理条件',href:'/index.html#exceptions'}};
 let fakeCatalog={total:1,counts:{needsData:0},sources:[{name:'fixture.xlsx'}],items:[fixtureCity]};
 await fake.addInitScript(()=>{window.EventSource=class{constructor(){window.testStream=this;this.handlers={};}addEventListener(name,fn){this.handlers[name]=fn;}close(){}emit(data){this.handlers.state?.({data:JSON.stringify(data)});}disconnect(){this.onerror?.();}};});
 await fake.route('**/api/**',async route=>{if(route.request().method()!=='GET')throw Error('Unexpected write');const url=new URL(route.request().url());let body;if(url.pathname.endsWith('/state'))body=fixtureState;else if(url.pathname.endsWith('/destinations'))body=url.searchParams.has('key')?{item:fixtureCity}:fakeCatalog;else return route.abort();await route.fulfill({json:body});});
 await fake.goto(base);await expect(fake.locator('.city-name')).toHaveText('测试目的地');await expect(fake.locator('#testBanner')).toBeVisible();await expect(fake.locator('.card-next')).toHaveText('查看处理条件');await expect(fake.locator('.city-card')).toContainText('待核验');await expect(fake.locator('.city-card')).not.toContainText('上架成功');checks.push('isolated unknown result protected and not counted as success');
 fixtureState.execution={state:'PAUSING'};fixtureState.active='fixture-batch';await fake.evaluate(s=>window.testStream.emit(s),fixtureState);await expect(fake.locator('#homeAttention')).toContainText('等待断点保存');await expect(fake.locator('#homeAttention')).toBeInViewport();await fake.screenshot({path:out+'pausing-isolated.png',fullPage:true});checks.push('in-flight pause remains visible as urgent banner without falsely claiming saved');
 fixtureState.execution={state:'PAUSED'};fixtureState.active=null;fixtureState.exceptions=[{destination:'测试目的地',captcha:true,reason:'需要人工验证'}];await fake.evaluate(s=>window.testStream.emit(s),fixtureState);await expect(fake.locator('#homeAttention')).toContainText('等待人工验证');await expect(fake.locator('#homeAttention')).toContainText('专用 Chrome');await fake.screenshot({path:out+'captcha-isolated.png',fullPage:true});checks.push('manual CAPTCHA takes priority without auto-solving');
 await fake.evaluate(()=>window.testStream.disconnect());await expect(fake.locator('#connectionNotice')).toBeVisible();await expect(fake.locator('#loginStatus')).toHaveText('登录状态待检查');await fake.evaluate(s=>window.testStream.emit(s),fixtureState);await expect(fake.locator('#connectionNotice')).toBeHidden();checks.push('disconnect and reconnect restore backend state');
 fixtureState.exceptions=[];fixtureState.execution={state:'IDLE'};fakeCatalog={total:0,counts:{needsData:0},sources:[],items:[]};await fake.reload();await expect(fake.locator('#catalogSource')).toContainText('还没有导入资料');await expect(fake.locator('#destinationCard')).toContainText('从你的第一个目的地开始');await expect(fake.locator('#globeMarkers button')).toHaveCount(0);await fake.screenshot({path:out+'empty-isolated.png'});checks.push('empty catalogue has no invented featured cities');
 await fake.close();
 const after=await fetch(base+'/api/v1/state').then(r=>r.json());assert.equal(after.active,null);assert.equal(after.settings.executionEnabled,false);assert.deepEqual(after.records.map(x=>x.itemId).sort(),before.records.map(x=>x.itemId).sort());assert.equal(after.batch.id,before.batch.id);assert.deepEqual(writes,[]);assert.deepEqual(errors,[]);
 const report={at:new Date().toISOString(),checks,layouts,errors,writes,passed:checks.length,recordCount:after.records.length,newRealPublications:0,kernel:after.kernel};await writeFile(out+'ui-qa.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();}
